const $=s=>document.querySelector(s),host=$('#canvas'),statusEl=$('#status'),timerEl=$('#timer'),countdown=$('#countdown'),events=$('#events');
const countEl=$('#playerCount'),namesEl=$('#names'),lineupEl=$('#lineup'),intro=$('#intro'),startBtn=$('#start'),againBtn=$('#again');
const resultEl=$('#results'),winnerEl=$('#winner'),standingEl=$('#standing'),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');host.append(canvas);
const animals=[['토끼','🐰','rabbit'],['원숭이','🐵','monkey'],['고양이','🐱','cat'],['닭','🐔','chicken'],['판다','🐼','panda'],['여우','🦊','fox'],['강아지','🐶','puppy'],['호랑이','🐯','tiger']];
const WORLD_FINISH=2500,LANE_H=66;
let W=960,H=720,dpr=1,ready=false,running=false,last=performance.now(),startedAt=0,cameraX=0,racers=[],obstacles=[],effects=[],finishOrder=[],sprites=[];

function resize(){const r=host.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,1.5);W=Math.max(620,r.width);H=Math.max(560,r.height);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true}addEventListener('resize',resize);resize();
function trackTop(){return (H-racers.length*LANE_H)/2}function laneY(i){return trackTop()+(i+.5)*LANE_H}

function removeChecker(img){const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data,w=c.width,h=c.height,seen=new Uint8Array(w*h),q=new Int32Array(w*h);let head=0,tail=0;const bg=p=>{const i=p*4,r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);return mx>198&&mx-mn<18};const add=p=>{if(p>=0&&p<w*h&&!seen[p]&&bg(p)){seen[p]=1;q[tail++]=p}};for(let i=0;i<w;i++){add(i);add((h-1)*w+i)}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1)}while(head<tail){const p=q[head++],px=p%w;d[p*4+3]=0;if(px)add(p-1);if(px<w-1)add(p+1);add(p-w);add(p+w)}x.putImageData(im,0,0);return c}
function isolateFrame(sheet,index){const sw=Math.floor(sheet.width/6),sh=sheet.height,sx=index*sw,c=document.createElement('canvas');c.width=sw;c.height=sh;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(sheet,sx,0,sw,sh,0,0,sw,sh);const im=x.getImageData(0,0,sw,sh),d=im.data,n=sw*sh,lab=new Uint16Array(n),q=new Int32Array(n);let id=0,best=0,bestN=0;for(let p=0;p<n;p++){if(lab[p]||d[p*4+3]<24)continue;id++;let h=0,t=0,size=0;lab[p]=id;q[t++]=p;while(h<t){const z=q[h++],zx=z%sw;size++;const add=v=>{if(v>=0&&v<n&&!lab[v]&&d[v*4+3]>=24){lab[v]=id;q[t++]=v}};if(zx)add(z-1);if(zx<sw-1)add(z+1);add(z-sw);add(z+sw)}if(size>bestN){bestN=size;best=id}}let minX=sw,minY=sh,maxX=0,maxY=0;for(let p=0;p<n;p++){if(lab[p]!==best)d[p*4+3]=0;else{const px=p%sw,py=p/sw|0;minX=Math.min(minX,px);maxX=Math.max(maxX,px);minY=Math.min(minY,py);maxY=Math.max(maxY,py)}}x.putImageData(im,0,0);const pad=4,t=document.createElement('canvas');t.width=maxX-minX+1+pad*2;t.height=maxY-minY+1+pad*2;t.getContext('2d').drawImage(c,minX,minY,maxX-minX+1,maxY-minY+1,pad,pad,maxX-minX+1,maxY-minY+1);return t}
const loadImage=src=>new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src});
async function loadSprites(){const imgs=await Promise.all(animals.map(a=>loadImage(`assets/${a[2]}-cycle.png?v=1`)));sprites=imgs.map(img=>{const clean=removeChecker(img);return Array.from({length:6},(_,i)=>isolateFrame(clean,i))});ready=true;statusEl.textContent='준비 완료'}

function rebuildInputs(){const n=+countEl.value,old=[...namesEl.querySelectorAll('input')].map(x=>x.value);namesEl.innerHTML='';for(let i=0;i<n;i++){const l=document.createElement('label');l.innerHTML=`<span>${animals[i][1]} ${i+1}</span><input value="${old[i]||animals[i][0]}">`;l.querySelector('input').oninput=rebuildLineup;namesEl.append(l)}rebuildLineup();intro.hidden=false;resetRace()}function rebuildLineup(){lineupEl.innerHTML=[...namesEl.querySelectorAll('input')].map((x,i)=>`<div><span>${animals[i][1]}</span><b>${x.value||animals[i][0]}</b></div>`).join('')}countEl.onchange=rebuildInputs;
function announce(t){const s=document.createElement('span');s.textContent=t;events.prepend(s);setTimeout(()=>s.remove(),2200)}
function resetRace(){running=false;cameraX=0;finishOrder=[];effects=[];resultEl.hidden=true;events.innerHTML='';timerEl.textContent='0.0';const inputs=[...namesEl.querySelectorAll('input')];racers=inputs.map((x,i)=>({i,name:x.value||animals[i][0],x:105,speed:0,base:122+Math.random()*15,phase:Math.random()*4,boost:0,tired:0,stun:0,jumpY:0,vy:0,shield:0,attack:0,attackFired:false,target:null,attackCd:1.2+Math.random()*2.5,finished:false,time:0}));obstacles=[];for(let i=0;i<racers.length;i++)for(let k=0;k<4;k++)obstacles.push({lane:i,x:500+k*480+(Math.random()-.5)*120,kind:Math.random()<.5?'cone':'box',shown:0,hit:new Set()});statusEl.textContent=ready?'준비 완료':'이미지 준비 중'}
function beginAttack(r,target){r.attack=.5;r.attackFired=false;r.target=target;r.attackCd=2.5+Math.random()*2.2;announce(`⚾ ${r.name}, 선두 ${target.name} 조준!`)}
function fireBall(r){if(!r.target||r.target.finished)return;effects.push({kind:'ball',x:r.x,y:laneY(r.i)-10,target:r.target,life:.62,max:.62});announce(`${r.name} 공을 던집니다!`)}
function tryAttack(r,dt){r.attackCd-=dt;if(r.attackCd>0||r.attack>0||r.stun||r.jumpY||r.finished)return;const active=racers.filter(x=>!x.finished),leader=[...active].sort((a,b)=>b.x-a.x)[0];if(r!==leader&&leader.shield<=0&&Math.random()<.7){leader.shield=1;beginAttack(r,leader)}else r.attackCd=.55}

function update(dt){const elapsed=(performance.now()-startedAt)/1000;timerEl.textContent=elapsed.toFixed(1);for(const r of racers){if(r.finished)continue;r.phase+=dt*(r.boost?18:r.tired?6:11);r.shield=Math.max(0,r.shield-dt);r.boost=Math.max(0,r.boost-dt);r.tired=Math.max(0,r.tired-dt);r.stun=Math.max(0,r.stun-dt);tryAttack(r,dt);if(r.attack>0){r.attack-=dt;if(!r.attackFired&&r.attack<.23){r.attackFired=true;fireBall(r)}}if(!r.boost&&!r.tired&&Math.random()<dt*.035){r.boost=1.25;announce(`💨 ${r.name} 부스터!`)}if(!r.boost&&!r.tired&&Math.random()<dt*.02){r.tired=1.15;announce(`💦 ${r.name} 잠시 지쳤습니다`)}const mul=r.stun?.2:r.tired?.58:r.boost?1.65:r.attack>.22?.72:1;r.speed+=(r.base*mul-r.speed)*Math.min(1,dt*4.5);r.x+=r.speed*dt;if(r.jumpY){r.vy+=610*dt;r.jumpY+=r.vy*dt;if(r.jumpY>=0){r.jumpY=0;r.vy=0}}for(const o of obstacles){if(o.lane!==r.i||o.hit.has(r)||Math.abs(o.x-r.x)>20)continue;o.hit.add(r);if(Math.random()<.7){r.jumpY=-2;r.vy=-255;announce(`✨ ${r.name} 장애물 점프!`)}else{r.stun=.72;r.speed*=.15;announce(`💥 ${r.name} 장애물 충돌!`)}}if(r.x>=WORLD_FINISH){r.x=WORLD_FINISH;r.finished=true;r.time=elapsed;finishOrder.push(r);announce(`${finishOrder.length}위 ${r.name} 결승 통과!`)}}
  const active=racers.filter(r=>!r.finished),leader=active.length?[...active].sort((a,b)=>b.x-a.x)[0]:racers[0],target=Math.max(0,Math.min(WORLD_FINISH-W*.72,leader.x-W*.34));cameraX+=(target-cameraX)*Math.min(1,dt*2.6);
  for(const o of obstacles)if(racers.some(r=>o.x-r.x<W*.25))o.shown=Math.min(1,o.shown+dt*3);
  for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;if(e.kind==='ball'&&e.life<=0&&e.target&&!e.target.finished){e.target.stun=.8;e.target.speed*=.18;e.target.shield=.8;effects.push({kind:'stars',x:e.target.x,y:laneY(e.target.i),life:.65});announce(`😵 ${e.target.name} 공에 맞았습니다!`)}if(e.life<=0)effects.splice(i,1)}if(finishOrder.length===racers.length)finish()}
function finish(){running=false;statusEl.textContent='경주 완료';winnerEl.textContent=`🏆 ${finishOrder[0].name} 우승`;standingEl.innerHTML=finishOrder.map(r=>`<li><b>${r.name}</b> — ${r.time.toFixed(2)}초</li>`).join('');resultEl.hidden=false;startBtn.disabled=false}

function roundRect(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill()}
function drawBackground(){const sky=ctx.createLinearGradient(0,0,0,H);sky.addColorStop(0,'#83d9f4');sky.addColorStop(.5,'#d7f5ff');sky.addColorStop(.51,'#70c66d');sky.addColorStop(1,'#3b9e54');ctx.fillStyle=sky;ctx.fillRect(0,0,W,H);for(let wx=-200;wx<WORLD_FINISH+500;wx+=260){const x=wx-cameraX*.55;if(x<-150||x>W+150)continue;ctx.fillStyle=wx%520?'#5eb460':'#4ca658';ctx.beginPath();ctx.arc(x,H*.39,105,Math.PI,0);ctx.fill()}const top=trackTop(),height=racers.length*LANE_H,start=55-cameraX,end=WORLD_FINISH+100-cameraX;roundRect(start,top,end-start,height,18,'#e9c98e');for(let i=0;i<=racers.length;i++){const y=top+i*LANE_H;ctx.strokeStyle='#fff9';ctx.lineWidth=2;ctx.setLineDash([18,13]);ctx.beginPath();ctx.moveTo(Math.max(-20,start),y);ctx.lineTo(Math.min(W+20,end),y);ctx.stroke()}ctx.setLineDash([]);for(let wx=300;wx<WORLD_FINISH;wx+=300){const x=wx-cameraX;ctx.fillStyle='#c19b66';ctx.fillRect(x,top,x%600?10:16,height)}drawFinish(top,height);ctx.font='700 11px sans-serif';ctx.textBaseline='middle';racers.forEach((r,i)=>{roundRect(10,laneY(i)-11,78,22,11,'#17364cdd');ctx.fillStyle='#fff';ctx.fillText(`${i+1} ${r.name}`,18,laneY(i))})}
function drawFinish(top,height){const x=WORLD_FINISH-cameraX;if(x<-80||x>W+120)return;ctx.fillStyle='#fff';ctx.fillRect(x-7,top,14,height);const tile=Math.max(16,LANE_H/2);for(let y=top;y<top+height;y+=tile)for(let q=0;q<2;q++){ctx.fillStyle=((y-top)/tile+q)%2<1?'#182331':'#fff';ctx.fillRect(x-7+q*7,y,7,tile)}ctx.fillStyle='#18344d';ctx.fillRect(x-20,top-44,40,height+55);ctx.fillRect(x-90,top-55,180,28);ctx.fillStyle='#ffe43c';ctx.font='900 20px DM Mono';ctx.textAlign='center';ctx.fillText('FINISH',x,top-36);ctx.textAlign='left'}
function drawObstacle(o){if(!o.shown)return;const x=o.x-cameraX,y=laneY(o.lane);if(x<-40||x>W+40)return;ctx.save();ctx.translate(x,y);ctx.scale(o.shown,o.shown);if(o.kind==='cone'){ctx.fillStyle='#ff683d';ctx.beginPath();ctx.moveTo(0,-20);ctx.lineTo(-14,17);ctx.lineTo(14,17);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-9,-1,18,5)}else{roundRect(-17,-16,34,32,4,'#8b5b32');ctx.strokeStyle='#d8a060';ctx.lineWidth=3;ctx.strokeRect(-14,-13,28,26)}ctx.restore()}
function drawRacer(r){const x=r.x-cameraX;if(x<-100||x>W+100)return;let frame=r.attack>0?(r.attack>.23?4:5):Math.floor(r.phase)%4;const sprite=sprites[r.i]?.[frame];if(!sprite)return;const size=58,ratio=sprite.width/sprite.height,bob=r.stun?Math.sin(r.phase*2)*4:Math.abs(Math.sin(r.phase*Math.PI))*3;ctx.save();ctx.translate(x,laneY(r.i)+r.jumpY-bob);ctx.rotate((r.boost?.13:r.tired?-.06:0)+(r.stun?Math.sin(r.phase*3)*.15:0));if(r.boost){ctx.globalAlpha=.2;for(let i=1;i<=3;i++)ctx.drawImage(sprite,-size*ratio/2-i*12,-size/2,size*ratio,size);ctx.globalAlpha=1}ctx.drawImage(sprite,-size*ratio/2,-size/2,size*ratio,size);ctx.restore();if(r.tired){ctx.fillStyle='#45bce8';ctx.beginPath();ctx.arc(x+24,laneY(r.i)-25,4,0,Math.PI*2);ctx.fill()}}
function drawEffects(){for(const e of effects){if(e.kind==='ball'){const p=1-e.life/e.max,x=e.x+(e.target.x-e.x)*p-cameraX,y=e.y+(laneY(e.target.i)-e.y)*p-Math.sin(p*Math.PI)*60;ctx.fillStyle='#fff';ctx.strokeStyle='#d83d3d';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.stroke()}else{ctx.fillStyle='#ffe335';ctx.font='24px sans-serif';ctx.fillText('✦',e.x-cameraX-10,e.y-18)}}}
function render(){drawBackground();obstacles.forEach(drawObstacle);racers.forEach(drawRacer);drawEffects()}
async function start(){if(!ready)return;intro.hidden=true;resetRace();startBtn.disabled=true;for(const v of ['3','2','1','GO!']){countdown.textContent=v;await new Promise(r=>setTimeout(r,v==='GO!'?550:520))}countdown.textContent='';startedAt=performance.now();running=true;statusEl.textContent='경주 중'}startBtn.onclick=start;againBtn.onclick=start;
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.04);last=now;if(running)update(dt);render()}
rebuildInputs();loadSprites().then(()=>{resetRace();requestAnimationFrame(loop)}).catch(e=>{statusEl.textContent='동물 애니메이션 로딩 실패';console.error(e)});
