(()=>{"use strict";
const cardEl=document.querySelector("#card"),cardTrail=document.querySelector("#cardTrail"),remainingEl=document.querySelector("#remaining"),streakEl=document.querySelector("#streak"),bestEl=document.querySelector("#best"),messageEl=document.querySelector("#message"),blackButton=document.querySelector("#blackButton"),redButton=document.querySelector("#redButton"),restartButton=document.querySelector("#restartButton");
const suits=["♠","♥","♦","♣"],rankNames={1:"A",11:"J",12:"Q",13:"K"};let deck=[],streak=0,best=Number(localStorage.getItem("blackred-best")||0),locked=false;
function shuffledDeck(){const cards=[];for(const suit of suits){for(let rank=1;rank<=13;rank++)cards.push({rank,suit,joker:false,color:suit==="♥"||suit==="♦"?"red":"black"})}cards.push({joker:true},{joker:true});for(let i=cards.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[cards[i],cards[j]]=[cards[j],cards[i]]}return cards}
function rankLabel(rank){return rankNames[rank]||String(rank)}
function renderBack(){cardEl.className="card back";cardEl.innerHTML="<b>?</b>"}
function renderCard(card){cardEl.className="card reveal";if(card.joker){cardEl.classList.add("joker");cardEl.innerHTML='<div class="corner">★</div><div class="suit">JOKER</div><div class="corner bottom">★</div>';return}if(card.color==="red")cardEl.classList.add("red");const rank=rankLabel(card.rank);cardEl.innerHTML=`<div class="corner"><b>${rank}</b><span>${card.suit}</span></div><div class="suit">${card.suit}</div><div class="corner bottom"><b>${rank}</b><span>${card.suit}</span></div>`}
function keepCard(){const past=cardEl.cloneNode(true);past.removeAttribute("id");past.removeAttribute("aria-live");past.classList.remove("reveal");past.classList.add("past-card");cardTrail.insertBefore(past,cardEl);renderBack();requestAnimationFrame(()=>cardEl.scrollIntoView({behavior:"smooth",block:"nearest",inline:"end"}))}
function setButtons(enabled){blackButton.disabled=!enabled;redButton.disabled=!enabled}
function draw(){if(deck.length===0)deck=shuffledDeck();const card=deck.pop();remainingEl.textContent=deck.length;return card}
function choose(color){if(locked)return;locked=true;setButtons(false);const card=draw(),win=card.joker||card.color===color;renderCard(card);if(win){streak++;best=Math.max(best,streak);localStorage.setItem("blackred-best",best);streakEl.textContent=streak;bestEl.textContent=best;messageEl.textContent=card.joker?"조커! 선택과 관계없이 승리!":"정답! 연승이 이어집니다.";messageEl.className="message win";setTimeout(()=>{keepCard();messageEl.textContent="나올 카드의 색을 선택하세요.";messageEl.className="message";locked=false;setButtons(true)},1100)}else{messageEl.textContent=`${card.color==="red"?"레드":"블랙"} 카드였습니다. 아쉽지만 틀렸어요.`;messageEl.className="message lose";restartButton.hidden=false}}
function reset(){deck=shuffledDeck();streak=0;locked=false;streakEl.textContent="0";bestEl.textContent=best;remainingEl.textContent=deck.length;cardTrail.querySelectorAll(".past-card").forEach(card=>card.remove());renderBack();messageEl.textContent="나올 카드의 색을 선택하세요.";messageEl.className="message";restartButton.hidden=true;setButtons(true)}
blackButton.addEventListener("click",()=>choose("black"));redButton.addEventListener("click",()=>choose("red"));restartButton.addEventListener("click",reset);addEventListener("keydown",event=>{if(event.key.toLowerCase()==="b"||event.key==="ArrowLeft")choose("black");if(event.key.toLowerCase()==="r"||event.key==="ArrowRight")choose("red")});reset();
})();
