(()=>{"use strict";
const currentEl=document.querySelector("#currentCard"),nextEl=document.querySelector("#nextCard"),streakEl=document.querySelector("#streak"),bestEl=document.querySelector("#best"),messageEl=document.querySelector("#message"),lowButton=document.querySelector("#lowButton"),highButton=document.querySelector("#highButton"),restartButton=document.querySelector("#restartButton");
const suits=["♠","♥","♦","♣"],rankNames={1:"A",11:"J",12:"Q",13:"K"};let currentCard=null,streak=0,best=Number(localStorage.getItem("highlow-best")||0),locked=false;
function numericCard(exclude=null){let rank;do{rank=1+Math.floor(Math.random()*13)}while(rank===exclude);return{rank,suit:suits[Math.floor(Math.random()*suits.length)],joker:false}}
function nextCandidate(){const pool=[];for(let rank=1;rank<=13;rank++){if(rank===currentCard.rank)continue;for(const suit of suits)pool.push({rank,suit,joker:false})}pool.push({joker:true},{joker:true});return pool[Math.floor(Math.random()*pool.length)]}
function rankLabel(rank){return rankNames[rank]||String(rank)}
function renderCard(el,card,hidden=false){el.className="card";el.innerHTML="";if(hidden){el.classList.add("back");el.innerHTML="<b>?</b>";return}if(card.joker){el.classList.add("joker");el.innerHTML='<div class="corner">★</div><div class="suit">JOKER</div><div class="corner bottom">★</div>';return}if(card.suit==="♥"||card.suit==="♦")el.classList.add("red");const rank=rankLabel(card.rank);el.innerHTML=`<div class="corner"><b>${rank}</b><span>${card.suit}</span></div><div class="suit">${card.suit}</div><div class="corner bottom"><b>${rank}</b><span>${card.suit}</span></div>`}
function setButtons(enabled){lowButton.disabled=!enabled;highButton.disabled=!enabled}
function isWin(choice,next){if(next.joker)return{win:true,reason:"조커! 무조건 승리"};if(currentCard.rank===1||next.rank===1)return{win:true,reason:"A는 1 또는 14! 승리"};const win=choice==="high"?next.rank>currentCard.rank:next.rank<currentCard.rank;return{win,reason:win?"정답! 연승이 이어집니다.":"아쉽지만 틀렸어요."}}
function choose(choice){if(locked)return;locked=true;setButtons(false);const next=nextCandidate(),result=isWin(choice,next);renderCard(nextEl,next);messageEl.textContent=result.reason;messageEl.className=`message ${result.win?"win":"lose"}`;if(result.win){streak++;best=Math.max(best,streak);localStorage.setItem("highlow-best",best);streakEl.textContent=streak;bestEl.textContent=best;setTimeout(()=>{currentCard=next.joker?numericCard(currentCard.rank):next;renderCard(currentEl,currentCard);renderCard(nextEl,null,true);messageEl.textContent="다음 카드가 더 높을지 낮을지 선택하세요.";messageEl.className="message";locked=false;setButtons(true)},1150)}else{restartButton.hidden=false}}
function reset(){streak=0;locked=false;currentCard=numericCard();streakEl.textContent="0";bestEl.textContent=best;renderCard(currentEl,currentCard);renderCard(nextEl,null,true);messageEl.textContent="다음 카드가 더 높을지 낮을지 선택하세요.";messageEl.className="message";restartButton.hidden=true;setButtons(true)}
lowButton.addEventListener("click",()=>choose("low"));highButton.addEventListener("click",()=>choose("high"));restartButton.addEventListener("click",reset);addEventListener("keydown",event=>{if(event.key==="ArrowDown")choose("low");if(event.key==="ArrowUp")choose("high")});reset();
})();
