(()=>{"use strict";
const canvas=document.querySelector("#gameCanvas"),ctx=canvas.getContext("2d"),stage=document.querySelector("#stage"),start=document.querySelector("#startButton"),progress=document.querySelector("#progress"),status=document.querySelector("#status"),soundButton=document.querySelector("#soundButton"),slots=[...document.querySelectorAll("#results i")];
let w=900,h=600,dpr=1,shot=null,running=false,soundOn=false,audio,last=performance.now(),flash=0,smoke=[];
function resize(){const r=stage.getBoundingClientRect();w=Math.max(320,r.width);h=Math.max(480,r.height);dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
function tone(freq,d=.09,type="square",gain=.035){if(!soundOn)return;audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function background(){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#123b58");g.addColorStop(.64,"#0c2941");g.addColorStop(1,"#091a2c");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.22;ctx.fillStyle="#d9f6ff";for(let i=0;i<42;i++){const x=(i*97.3)%w,y=(i*i*13.7)%(h*.68);ctx.fillRect(x,y,1+(i%3===0),1+(i%4===0))}ctx.globalAlpha=1;ctx.fillStyle="#133a35";ctx.beginPath();ctx.moveTo(0,h);ctx.quadraticCurveTo(w*.18,h*.68,w*.4,h*.83);ctx.quadraticCurveTo(w*.72,h*.65,w,h*.8);ctx.lineTo(w,h);ctx.fill()}
function cannon(){const x=w*.5,y=h*.84;ctx.save();ctx.translate(x,y);ctx.fillStyle="#182535";ctx.strokeStyle="#44576a";ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,18,43,Math.PI,0);ctx.lineTo(43,38);ctx.lineTo(-43,38);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle="#27394c";ctx.save();ctx.rotate(-Math.PI/2);ctx.fillRect(-25,-15,92,30);ctx.strokeRect(-25,-15,92,30);ctx.restore();ctx.fillStyle="#111b28";ctx.beginPath();ctx.arc(-35,35,18,0,Math.PI*2);ctx.arc(35,35,18,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawBall(){if(!shot)return;const t=Math.min(1,(performance.now()-shot.started)/350),ease=1-Math.pow(1-t,3),x=w*.5+Math.sin(t*Math.PI)*w*.08,y=h*.72-ease*h*.52,scale=.65+ease*.75,r=26*scale;ctx.save();ctx.translate(x,y);ctx.shadowBlur=30;ctx.shadowColor="#f7e84b";const g=ctx.createRadialGradient(-r*.3,-r*.35,2,0,0,r);g.addColorStop(0,"#fffbd0");g.addColorStop(.38,"#f7e84b");g.addColorStop(1,"#b38a17");ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#142031";ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`700 ${Math.round(r*1.15)}px Space Grotesk`;ctx.fillText(shot.number,0,2);ctx.restore();if(t>=1&&!shot.done){shot.done=true;finishShot()}}
function drawSmoke(dt){smoke.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.r+=dt*16;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle="#dce7e9";ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.globalAlpha=1;smoke=smoke.filter(p=>p.life>0)}
function loop(now){const dt=Math.min(.04,(now-last)/1000);last=now;background();cannon();drawSmoke(dt);drawBall();if(flash>0){ctx.fillStyle=`rgba(247,232,75,${flash})`;ctx.fillRect(0,0,w,h);flash=Math.max(0,flash-dt*2)}requestAnimationFrame(loop)}
const REPEAT_RATE=.40;
let current=0,lastNumber=null;
function nextNumber(){if(lastNumber===null)return 1+Math.floor(Math.random()*3);if(Math.random()<REPEAT_RATE)return lastNumber;return((lastNumber-1+(1+Math.floor(Math.random()*2)))%3)+1}
function fire(){const number=nextNumber();lastNumber=number;shot={number,started:performance.now(),done:false};flash=.17;for(let i=0;i<13;i++)smoke.push({x:w*.5+(Math.random()-.5)*20,y:h*.7+Math.random()*20,vx:(Math.random()-.5)*48,vy:-25-Math.random()*45,r:5+Math.random()*9,life:.45+Math.random()*.35});tone(86,.14,"sawtooth",.06);status.textContent=`${current+1}번째 포탄 발사!`}
function finishShot(){slots[current].textContent=shot.number;slots[current].classList.add("filled");current++;progress.textContent=`${current} / 7`;tone(480+shot.number*90,.12,"sine",.04);if(current<7)setTimeout(fire,150);else{running=false;start.disabled=false;start.querySelector("span").textContent="다시 7연발";status.textContent="일곱 발 발사 완료! 다시 시작할 수 있어요."}}
function begin(){if(running)return;running=true;current=0;lastNumber=null;shot=null;slots.forEach(s=>{s.textContent="—";s.classList.remove("filled")});progress.textContent="0 / 7";start.disabled=true;status.textContent="대포를 준비하고 있어요…";setTimeout(fire,350)}
start.addEventListener("click",begin);soundButton.addEventListener("click",()=>{soundOn=!soundOn;soundButton.textContent=soundOn?"SOUND ON":"SOUND OFF";soundButton.setAttribute("aria-pressed",soundOn);tone(660)});addEventListener("keydown",e=>{if((e.key===" "||e.key==="Enter")&&!running){e.preventDefault();begin()}});new ResizeObserver(resize).observe(stage);resize();requestAnimationFrame(loop);
})();
