(()=>{"use strict";
const $=s=>document.querySelector(s),canvas=$("#gameCanvas"),ctx=canvas.getContext("2d"),wrap=$("#canvasWrap"),ui={score:$("#score"),combo:$("#combo"),lives:$("#lives"),start:$("#startScreen"),pause:$("#pauseScreen"),over:$("#gameOverScreen"),final:$("#finalScore"),best:$("#bestScore"),sound:$("#soundButton"),pauseBtn:$("#pauseButton")};
let w=960,h=520,dpr=1,state="ready",last=0,time=0,score=0,combo=1,lives=3,meteorClock=0,shardClock=0,shake=0,pointer=false,sound=false,audio;
const keys=new Set(),meteors=[],shards=[],particles=[],stars=[],ship={x:480,y:440,target:480,radius:16,inv:0};
const star=(random=false)=>({x:Math.random()*w,y:random?Math.random()*h:-4,size:Math.random()*1.7+.3,speed:Math.random()*34+12,alpha:Math.random()*.65+.2});
function resize(){const r=wrap.getBoundingClientRect();w=Math.max(320,r.width);h=Math.max(320,r.height);dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ship.y=h-58;ship.x=Math.min(Math.max(ship.x,28),w-28);ship.target=ship.x;if(!stars.length)for(let i=0;i<110;i++)stars.push(star(true))}
function show(el){[ui.start,ui.pause,ui.over].forEach(x=>x.classList.remove("visible"));if(el)el.classList.add("visible")}
function tone(freq,d=.08,type="sine",gain=.035){if(!sound)return;audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function hud(){ui.score.textContent=Math.floor(score).toString().padStart(6,"0");ui.combo.textContent=`×${combo}`;ui.lives.textContent=(`${"◆ ".repeat(lives)}${"◇ ".repeat(3-lives)}`).trim()}
function reset(){score=0;combo=1;lives=3;time=0;meteorClock=0;shardClock=.5;shake=0;meteors.length=shards.length=particles.length=0;ship.x=w/2;ship.target=ship.x;ship.inv=0;hud();state="playing";show();last=performance.now();tone(420,.12,"triangle",.05)}
function pause(force){if(!["playing","paused"].includes(state))return;state=force??(state==="playing"?"paused":"playing");show(state==="paused"?ui.pause:null);ui.pauseBtn.textContent=state==="paused"?"RESUME":"PAUSE";if(state==="playing")last=performance.now()}
function end(){state="over";const final=Math.floor(score),best=Math.max(final,Number(localStorage.getItem("starglide-best")||0));localStorage.setItem("starglide-best",best);ui.final.textContent=final.toLocaleString("ko-KR");ui.best.textContent=best.toLocaleString("ko-KR");show(ui.over);tone(110,.5,"sawtooth",.04)}
function meteor(){const r=12+Math.random()*20;meteors.push({x:r+Math.random()*(w-r*2),y:-r-4,r,speed:135+time*5+Math.random()*95,drift:(Math.random()-.5)*34,rot:Math.random()*6.28,spin:(Math.random()-.5)*2.4})}
function shard(){shards.push({x:28+Math.random()*(w-56),y:-20,r:10,speed:120+time*2.3,rot:0})}
function burst(x,y,color,n=12){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*150;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.45,max:.8,color,size:1+Math.random()*3})}}
const hits=(a,b,p=0)=>Math.hypot(a.x-b.x,a.y-b.y)<a.radius+b.r-p;
function update(dt){time+=dt;score+=dt*(8+time*.15)*combo;ship.inv=Math.max(0,ship.inv-dt);shake=Math.max(0,shake-dt*18);const move=(keys.has("arrowleft")||keys.has("a")?-1:0)+(keys.has("arrowright")||keys.has("d")?1:0);if(move)ship.target+=move*430*dt;ship.target=Math.max(24,Math.min(w-24,ship.target));ship.x+=(ship.target-ship.x)*Math.min(1,dt*(pointer?15:9));stars.forEach(s=>{s.y+=s.speed*dt*(1+time/100);if(s.y>h+3)Object.assign(s,star())});meteorClock-=dt;shardClock-=dt;if(meteorClock<=0){meteor();meteorClock=Math.max(.19,.72-time*.009)*(.75+Math.random()*.5)}if(shardClock<=0){shard();shardClock=1.05+Math.random()*1.1}
for(let i=meteors.length-1;i>=0;i--){const m=meteors[i];m.y+=m.speed*dt;m.x+=m.drift*dt;m.rot+=m.spin*dt;if(m.y-m.r>h){meteors.splice(i,1);combo=Math.min(9,combo+1);continue}if(!ship.inv&&hits(ship,m,5)){meteors.splice(i,1);lives--;combo=1;ship.inv=1.25;shake=9;burst(ship.x,ship.y,"#ff6b7d",24);tone(90,.24,"square",.05);if(lives<=0)end()}}
for(let i=shards.length-1;i>=0;i--){const s=shards[i];s.y+=s.speed*dt;s.rot+=dt*2.8;if(s.y>h+20){shards.splice(i,1);continue}if(hits(ship,s,2)){shards.splice(i,1);score+=120*combo;combo=Math.min(9,combo+1);burst(s.x,s.y,"#66f7e5",15);tone(540+combo*35,.1)}}for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.98;p.vy*=.98;if(p.life<=0)particles.splice(i,1)}hud()}
function background(){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#080a1d");g.addColorStop(1,"#060713");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.52,h*.2,0,w*.52,h*.2,w*.65);glow.addColorStop(0,"rgba(103,68,200,.15)");glow.addColorStop(1,"transparent");ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);stars.forEach(s=>{ctx.globalAlpha=s.alpha;ctx.fillStyle="#d9dcff";ctx.fillRect(s.x,s.y,s.size,s.size*2.4)});ctx.globalAlpha=1}
function drawShip(){ctx.save();ctx.translate(ship.x,ship.y);if(ship.inv&&Math.floor(ship.inv*12)%2)ctx.globalAlpha=.22;const f=ctx.createLinearGradient(0,14,0,39);f.addColorStop(0,"#66f7e5");f.addColorStop(1,"transparent");ctx.fillStyle=f;ctx.beginPath();ctx.moveTo(-6,13);ctx.lineTo(0,34+Math.sin(time*20)*4);ctx.lineTo(6,13);ctx.fill();ctx.shadowBlur=22;ctx.shadowColor="#9b7bff";ctx.fillStyle="#e8e7ff";ctx.beginPath();ctx.moveTo(0,-22);ctx.lineTo(17,17);ctx.lineTo(0,10);ctx.lineTo(-17,17);ctx.closePath();ctx.fill();ctx.shadowBlur=14;ctx.shadowColor="#66f7e5";ctx.fillStyle="#66f7e5";ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(5,8);ctx.lineTo(-5,8);ctx.closePath();ctx.fill();ctx.restore()}
function drawMeteor(m){ctx.save();ctx.translate(m.x,m.y);ctx.rotate(m.rot);ctx.shadowBlur=18;ctx.shadowColor="rgba(255,107,125,.46)";const g=ctx.createRadialGradient(-m.r*.3,-m.r*.35,1,0,0,m.r);g.addColorStop(0,"#ff9a8d");g.addColorStop(.35,"#bd4d68");g.addColorStop(1,"#32172e");ctx.fillStyle=g;ctx.beginPath();for(let i=0;i<10;i++){const a=i/10*Math.PI*2,r=m.r*(.82+Math.sin(i*8.2+m.rot)*.14),x=Math.cos(a)*r,y=Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill();ctx.restore()}
function drawShard(s){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.rot);ctx.shadowBlur=24;ctx.shadowColor="#66f7e5";ctx.fillStyle="#d8fffa";ctx.beginPath();ctx.moveTo(0,-13);ctx.lineTo(9,0);ctx.lineTo(0,13);ctx.lineTo(-9,0);ctx.closePath();ctx.fill();ctx.restore()}
function draw(){ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);background();shards.forEach(drawShard);meteors.forEach(drawMeteor);particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.globalAlpha=1;drawShip();ctx.restore()}
function loop(now){const dt=Math.min(.034,(now-last)/1000||0);last=now;if(state==="playing")update(dt);draw();requestAnimationFrame(loop)}function point(e){ship.target=e.clientX-canvas.getBoundingClientRect().left;pointer=true}
$("#startButton").onclick=reset;$("#restartButton").onclick=reset;$("#resumeButton").onclick=()=>pause("playing");ui.pauseBtn.onclick=()=>pause();ui.sound.onclick=()=>{sound=!sound;ui.sound.textContent=sound?"SOUND ON":"SOUND OFF";ui.sound.setAttribute("aria-pressed",sound);tone(660)};addEventListener("keydown",e=>{if(["ArrowLeft","ArrowRight"," "].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.key===" "&&["ready","over"].includes(state))reset();if(["p","Escape"].includes(e.key))pause()});addEventListener("keyup",e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener("pointerdown",e=>{canvas.setPointerCapture(e.pointerId);point(e)});canvas.addEventListener("pointermove",e=>{if(e.buttons||e.pointerType==="touch")point(e)});canvas.addEventListener("pointerup",()=>pointer=false);addEventListener("blur",()=>state==="playing"&&pause("paused"));new ResizeObserver(resize).observe(wrap);resize();requestAnimationFrame(loop)
})();

