(()=>{"use strict";
const animals=[{emoji:"🐰",name:"토끼"},{emoji:"🦊",name:"여우"},{emoji:"🐯",name:"호랑이"},{emoji:"🐼",name:"판다"},{emoji:"🐸",name:"개구리"},{emoji:"🐵",name:"원숭이"},{emoji:"🐶",name:"강아지"},{emoji:"🐱",name:"고양이"}];
const obstacles=["🪨","🌳","💧","🕳️"];
const countEl=document.querySelector("#playerCount"),inputsEl=document.querySelector("#nameInputs"),tracksEl=document.querySelector("#tracks"),startButton=document.querySelector("#startButton"),shuffleButton=document.querySelector("#shuffleButton"),againButton=document.querySelector("#againButton"),statusEl=document.querySelector("#status"),timerEl=document.querySelector("#timer"),resultEl=document.querySelector("#result"),winnerAnimalEl=document.querySelector("#winnerAnimal"),winnerNameEl=document.querySelector("#winnerName"),standingsEl=document.querySelector("#standings");
let racers=[],finishers=[],timerId=null,startTime=0,running=false,animalOrder=[];
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char])}
function shuffle(values){const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function selectedNames(){return[...inputsEl.querySelectorAll("input")].map((input,index)=>input.value.trim()||`참가자 ${index+1}`)}
function renderInputs(preserveNames=true){const count=Number(countEl.value),old=preserveNames?selectedNames():[];if(animalOrder.length<count)animalOrder=shuffle(animals);inputsEl.innerHTML="";for(let i=0;i<count;i++){const label=document.createElement("label");label.className="name-input";label.innerHTML=`<span>${animalOrder[i].emoji}</span><input maxlength="10" value="${escapeHtml(old[i]||animalOrder[i].name)}" aria-label="${i+1}번 참가자 이름">`;inputsEl.append(label)}buildTracks()}
function buildTracks(){const names=selectedNames();finishers=[];racers=names.map((name,index)=>({name,animal:animalOrder[index],progress:0,finished:false,time:null,effect:"",effectUntil:0,obstacle:{emoji:obstacles[Math.floor(Math.random()*obstacles.length)],progress:30+Math.random()*43,passed:false}}));tracksEl.innerHTML=racers.map((racer,index)=>`<div class="track"><span class="lane-name">${index+1} · ${escapeHtml(racer.name)}</span><span class="obstacle" data-obstacle="${index}" style="left:${racer.obstacle.progress}%">${racer.obstacle.emoji}</span><span class="racer" data-racer="${index}"><span class="runner-avatar"><i class="runner-body"></i><i class="runner-leg front-a"></i><i class="runner-leg front-b"></i><i class="runner-leg back-a"></i><i class="runner-leg back-b"></i><i class="runner-head">${racer.animal.emoji}</i></span><em class="effect-label"></em></span></div>`).join("")}
function setLocked(value){countEl.disabled=value;shuffleButton.disabled=value;startButton.disabled=value;inputsEl.querySelectorAll("input").forEach(input=>input.disabled=value)}
function racerElement(racer){return tracksEl.querySelector(`[data-racer="${racers.indexOf(racer)}"]`)}
function setEffect(racer,type,duration,label,now){racer.effect=type;racer.effectUntil=now+duration;const element=racerElement(racer);element.classList.remove("dash","tired","attacked","attack","stumble","jump");element.classList.add(type);element.querySelector(".effect-label").textContent=label}
function clearEffect(racer){racer.effect="";racer.effectUntil=0;const element=racerElement(racer);element.classList.remove("dash","tired","attacked","attack","stumble","jump");element.querySelector(".effect-label").textContent=""}
function randomSkill(racer,now){if(racer.effect||racer.finished)return;const roll=Math.random();if(roll<.018){setEffect(racer,"dash",720,"🚀 부스터!",now);return}if(roll<.031){setEffect(racer,"tired",950,"💤 지침",now);return}if(roll<.043){const rivals=racers.filter(other=>other!==racer&&!other.finished);if(!rivals.length)return;const target=rivals[Math.floor(Math.random()*rivals.length)];target.progress=Math.max(0,target.progress-1.8);setEffect(racer,"attack",350,"⚡ 공격!",now);setEffect(target,"attacked",750,"💥 피격!",now)}}
function speedMultiplier(racer){return racer.effect==="dash"?2.15:racer.effect==="jump"?1.12:racer.effect==="tired"?.42:racer.effect==="attacked"?.52:racer.effect==="stumble"?.3:1}
function frame(){if(!running)return;const now=performance.now(),order=shuffle(racers.map((_,index)=>index).filter(index=>!racers[index].finished));for(const index of order){const racer=racers[index];if(racer.effect&&now>=racer.effectUntil)clearEffect(racer);randomSkill(racer,now);const burst=Math.random()<.06?Math.random()*1.3:0;racer.progress+=(.25+Math.random()*1.05+burst)*speedMultiplier(racer);if(!racer.obstacle.passed&&racer.progress>=racer.obstacle.progress){racer.obstacle.passed=true;const obstacle=tracksEl.querySelector(`[data-obstacle="${index}"]`);obstacle.classList.add("passed");if(Math.random()<.52){setEffect(racer,"jump",680,"🪽 점프!",now);obstacle.classList.add("jumped")}else{setEffect(racer,"stumble",720,"💫 충돌!",now);racer.progress=Math.max(0,racer.progress-1.5)}}const element=racerElement(racer),distance=Math.max(0,element.parentElement.clientWidth-element.offsetWidth-58);element.style.transform=`translateX(${Math.min(100,racer.progress)/100*distance}px)`;if(racer.progress>=100){racer.progress=100;racer.finished=true;racer.time=(now-startTime)/1000;finishers.push(racer);clearEffect(racer);element.classList.remove("running");element.classList.add("finished")}}timerEl.textContent=((now-startTime)/1000).toFixed(1);if(finishers.length===racers.length){finishRace();return}if(finishers.length>0)statusEl.textContent=`${finishers.length}명 완주 · 남은 동물도 달리는 중!`;timerId=setTimeout(frame,90)}
function start(){if(running)return;resultEl.hidden=true;buildTracks();running=true;setLocked(true);timerEl.textContent="0.0";statusEl.textContent="장애물과 공격을 뚫고 달리는 중!";tracksEl.querySelectorAll(".racer").forEach(element=>element.classList.add("running"));setTimeout(()=>{startTime=performance.now();frame()},700)}
function finishRace(){const winner=finishers[0];running=false;clearTimeout(timerId);setLocked(false);tracksEl.querySelectorAll(".racer").forEach(element=>element.classList.remove("running"));statusEl.textContent=`${winner.name} 우승!`;winnerAnimalEl.textContent=winner.animal.emoji;winnerNameEl.textContent=`${winner.name} 우승!`;standingsEl.innerHTML=finishers.map((racer,index)=>`<div class="standing"><b>${index+1}</b><span class="standing-animal">${racer.animal.emoji}</span><strong>${escapeHtml(racer.name)}</strong><time>${racer.time.toFixed(2)}초</time></div>`).join("");resultEl.hidden=false}
function resetRace(){resultEl.hidden=true;statusEl.textContent="참가자를 설정하고 경주를 시작하세요.";timerEl.textContent="0.0";buildTracks()}
countEl.addEventListener("change",()=>renderInputs(true));shuffleButton.addEventListener("click",()=>{animalOrder=shuffle(animals);renderInputs(false)});startButton.addEventListener("click",start);againButton.addEventListener("click",resetRace);animalOrder=shuffle(animals);renderInputs(false);
})();
