(()=>{"use strict";
const animals=[{emoji:"🐰",name:"토끼",fur:"#f4eee8"},{emoji:"🦊",name:"여우",fur:"#e98232"},{emoji:"🐯",name:"호랑이",fur:"#e88a2f"},{emoji:"🐼",name:"판다",fur:"#ececeb"},{emoji:"🐸",name:"개구리",fur:"#55a95c"},{emoji:"🐵",name:"원숭이",fur:"#98623e"},{emoji:"🐶",name:"강아지",fur:"#9a795d"},{emoji:"🐱",name:"고양이",fur:"#7f8b95"}];
const obstacleIcons=["🪨","🪵","💧","🚧"];
const $=selector=>document.querySelector(selector);
const countEl=$("#playerCount"),inputsEl=$("#nameInputs"),courseEl=$("#tracks"),startButton=$("#startButton"),shuffleButton=$("#shuffleButton"),againButton=$("#againButton"),statusEl=$("#status"),timerEl=$("#timer"),resultEl=$("#result"),winnerAnimalEl=$("#winnerAnimal"),winnerNameEl=$("#winnerName"),standingsEl=$("#standings");
let animalOrder=[],racers=[],finishers=[],timerId=0,startTime=0,running=false;
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char])}
function shuffle(values){const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function selectedNames(){return[...inputsEl.querySelectorAll("input")].map((input,index)=>input.value.trim()||`참가자 ${index+1}`)}
function renderInputs(preserve=true){const count=Number(countEl.value),old=preserve?selectedNames():[];if(animalOrder.length<count)animalOrder=shuffle(animals);inputsEl.innerHTML="";for(let i=0;i<count;i++){const label=document.createElement("label");label.className="name-input";label.innerHTML=`<span>${animalOrder[i].emoji}</span><input maxlength="10" value="${escapeHtml(old[i]||animalOrder[i].name)}" aria-label="${i+1}번 참가자 이름">`;inputsEl.append(label)}buildCourse()}
function avatarMarkup(racer){return`<span class="runner-avatar" style="--fur:${racer.animal.fur}"><i class="runner-body"></i><i class="runner-leg front-a"></i><i class="runner-leg front-b"></i><i class="runner-leg back-a"></i><i class="runner-leg back-b"></i><i class="runner-head">${racer.animal.emoji}</i></span>`}
function buildCourse(){const names=selectedNames();finishers=[];racers=names.map((name,index)=>({name,animal:animalOrder[index],progress:0,finished:false,time:0,effect:"",effectUntil:0,obstacle:{icon:obstacleIcons[Math.floor(Math.random()*obstacleIcons.length)],progress:28+Math.random()*44,passed:false}}));courseEl.innerHTML=`<div class="course-sky"></div><div class="track-surface">${Array.from({length:7},(_,i)=>`<i style="--line:${i}"></i>`).join("")}</div><div class="finish-gate"><span>FINISH</span></div><div class="progress-meter"><small>선두</small><i><b id="progressFill"></b></i></div>${racers.map((racer,index)=>`<span class="course-obstacle" data-obstacle="${index}">${racer.obstacle.icon}</span><span class="course-racer" data-racer="${index}"><b class="runner-name">${escapeHtml(racer.name)}</b>${avatarMarkup(racer)}<em class="effect-label"></em></span>`).join("")}`;racers.forEach((racer,index)=>{place(courseEl.querySelector(`[data-racer="${index}"]`),index,0);place(courseEl.querySelector(`[data-obstacle="${index}"]`),index,racer.obstacle.progress)})}
function place(element,lane,progress){const count=racers.length,p=Math.max(0,Math.min(100,progress))/100,left=6+88*(lane+.5)/count,bottom=6+p*78;element.style.left=`${left}%`;element.style.bottom=`${bottom}%`;element.style.transform="translate(-50%,50%)";element.style.zIndex=String(20+Math.round((1-p)*70))}
function setLocked(value){countEl.disabled=value;shuffleButton.disabled=value;startButton.disabled=value;inputsEl.querySelectorAll("input").forEach(input=>input.disabled=value)}
function racerElement(racer){return courseEl.querySelector(`[data-racer="${racers.indexOf(racer)}"]`)}
function setEffect(racer,type,duration,label,now){racer.effect=type;racer.effectUntil=now+duration;const el=racerElement(racer);el.classList.remove("boost","tired","attacked","attack","stumble","jump");el.classList.add(type);el.querySelector(".effect-label").textContent=label}
function clearEffect(racer){racer.effect="";racer.effectUntil=0;const el=racerElement(racer);el.classList.remove("boost","tired","attacked","attack","stumble","jump");el.querySelector(".effect-label").textContent=""}
function randomEvent(racer,now){if(racer.effect||racer.finished)return;const roll=Math.random();if(roll<.017){setEffect(racer,"boost",760,"🚀 부스터!",now);return}if(roll<.029){setEffect(racer,"tired",1000,"💤 지침",now);return}if(roll<.041){const targets=racers.filter(other=>other!==racer&&!other.finished);if(!targets.length)return;const target=targets[Math.floor(Math.random()*targets.length)];target.progress=Math.max(0,target.progress-2);setEffect(racer,"attack",360,"⚡ 공격!",now);setEffect(target,"attacked",760,"💥 피격!",now)}}
function multiplier(racer){return racer.effect==="boost"?2.2:racer.effect==="jump"?1.12:racer.effect==="tired"?.4:racer.effect==="attacked"?.5:racer.effect==="stumble"?.25:1}
function tick(){if(!running)return;const now=performance.now(),order=shuffle(racers.map((_,i)=>i).filter(i=>!racers[i].finished));for(const index of order){const racer=racers[index];if(racer.effect&&now>=racer.effectUntil)clearEffect(racer);randomEvent(racer,now);racer.progress+=(.22+Math.random()*.92+(Math.random()<.055?Math.random()*1.3:0))*multiplier(racer);if(!racer.obstacle.passed&&racer.progress>=racer.obstacle.progress){racer.obstacle.passed=true;const obstacle=courseEl.querySelector(`[data-obstacle="${index}"]`);if(Math.random()<.55){setEffect(racer,"jump",720,"점프!",now);obstacle.classList.add("cleared")}else{setEffect(racer,"stumble",850,"에고!",now);racer.progress=Math.max(0,racer.progress-1.8);obstacle.classList.add("hit")}}const el=racerElement(racer);place(el,index,racer.progress);if(racer.progress>=100){racer.progress=100;racer.finished=true;racer.time=(now-startTime)/1000;finishers.push(racer);clearEffect(racer);el.classList.add("finished")}}const leader=Math.max(...racers.map(r=>r.progress));const fill=$("#progressFill");if(fill)fill.style.height=`${Math.min(100,leader)}%`;timerEl.textContent=((now-startTime)/1000).toFixed(1);statusEl.textContent=finishers.length?`${finishers.length}명 완주 · 경주 계속!`:"달리는 중… 부스터와 장애물을 주의하세요!";if(finishers.length===racers.length){finishRace();return}timerId=setTimeout(tick,85)}
function start(){if(running)return;resultEl.hidden=true;buildCourse();running=true;setLocked(true);timerEl.textContent="0.0";statusEl.textContent="준비…";courseEl.querySelectorAll(".course-racer").forEach(el=>el.classList.add("running"));setTimeout(()=>{startTime=performance.now();statusEl.textContent="GO!";tick()},700)}
function finishRace(){const winner=finishers[0];running=false;clearTimeout(timerId);setLocked(false);statusEl.textContent=`${winner.name} 우승!`;winnerAnimalEl.textContent=winner.animal.emoji;winnerNameEl.textContent=`${winner.name} 우승!`;standingsEl.innerHTML=finishers.map((racer,index)=>`<div class="standing"><b>${index+1}</b><span class="standing-animal">${racer.animal.emoji}</span><strong>${escapeHtml(racer.name)}</strong><time>${racer.time.toFixed(2)}초</time></div>`).join("");resultEl.hidden=false}
function reset(){resultEl.hidden=true;statusEl.textContent="참가자를 설정하고 경주를 시작하세요.";timerEl.textContent="0.0";buildCourse()}
countEl.addEventListener("change",()=>renderInputs(true));shuffleButton.addEventListener("click",()=>{animalOrder=shuffle(animals);renderInputs(false)});startButton.addEventListener("click",start);againButton.addEventListener("click",reset);animalOrder=shuffle(animals);renderInputs(false);
})();
