const coin=document.querySelector('#coin'),guide=document.querySelector('#guide'),result=document.querySelector('#result'),resultTitle=result.querySelector('h2'),resultText=result.querySelector('strong'),historyEl=document.querySelector('#history'),streakEl=document.querySelector('#streak'),continueBtn=document.querySelector('#continue');
const choiceBtns=[...document.querySelectorAll('.choices button')];let pick=null,running=false,angle=0,streak=0,attempts=[],resetStreakOnContinue=false;
function fairSide(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%2===0?'front':'back'}
function renderHistory(){streakEl.textContent=`${streak}회`;historyEl.innerHTML=attempts.length?attempts.map(x=>`<div><span>${x.pick==='front'?'앞면':'뒷면'} 선택</span><b class="${x.win?'success':'failure'}">${x.win?'성공':'실패'}</b></div>`).join(''):'<p>앞·뒤를 선택해 도전하세요.</p>'}
choiceBtns.forEach(btn=>btn.onclick=()=>{if(running)return;pick=btn.dataset.pick;choiceBtns.forEach(x=>{x.classList.toggle('selected',x===btn);x.disabled=true});guide.textContent=`${pick==='front'?'앞면':'뒷면'} 선택! 동전을 던집니다…`;setTimeout(flip,180)});
function flip(){if(!pick||running)return;running=true;const side=fairSide(),start=performance.now(),from=angle,tau=Math.PI*2,current=((angle%tau)+tau)%tau,desired=side==='back'?Math.PI:0,delta=tau*(9+Math.floor(Math.random()*4))+((desired-current+tau)%tau),target=angle+delta,duration=3100;function frame(now){const t=Math.min(1,(now-start)/duration),p=1-Math.pow(1-t,4);angle=from+(target-from)*p;coin.style.transform=`translateY(${-Math.sin(t*Math.PI)*85}px) rotateY(${angle}rad) rotateZ(${Math.sin(t*Math.PI*2)*10}deg)`;if(t<1)requestAnimationFrame(frame);else finish(side)}requestAnimationFrame(frame)}
function finish(side){running=false;angle=((angle%(Math.PI*2))+Math.PI*2)%(Math.PI*2);coin.style.transform=`rotateY(${angle}rad)`;const win=pick===side;resultTitle.textContent=side==='front'?'앞면!':'뒷면!';resultText.textContent=win?'예측 성공 🎉':'예측 실패';resultText.style.color=win?'#ffe04c':'#ff8793';if(win)streak+=1;resetStreakOnContinue=!win;attempts.unshift({pick,side,win});attempts=attempts.slice(0,10);renderHistory();continueBtn.textContent=win?'도전':'다시 하기';result.hidden=false;guide.textContent=win?'연속 성공에 도전하세요!':'다시 하기를 누르면 연속 기록이 초기화됩니다.'}
function reset(){if(resetStreakOnContinue){streak=0;resetStreakOnContinue=false;renderHistory()}result.hidden=true;pick=null;choiceBtns.forEach(x=>{x.disabled=false;x.classList.remove('selected')});guide.textContent='앞면이나 뒷면을 선택하면 바로 시작합니다.'}
continueBtn.onclick=reset;renderHistory();
