const coin=document.querySelector('#coin'),guide=document.querySelector('#guide'),toss=document.querySelector('#toss'),result=document.querySelector('#result'),resultTitle=result.querySelector('h2'),resultText=result.querySelector('strong'),historyEl=document.querySelector('#history');
const choiceBtns=[...document.querySelectorAll('.choices button')],again=document.querySelector('#again');let pick=null,running=false,angle=0,history=[];
function fairSide(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%2===0?'front':'back'}
function renderHistory(){historyEl.innerHTML=history.length?history.map((x,i)=>`<div><span>${i+1}회 · ${x.pick==='front'?'앞면':'뒷면'} 선택</span><b class="${x.side}-result">${x.side==='front'?'앞':'뒤'} ${x.win?'✓':'✕'}</b></div>`).join(''):'<p>아직 기록이 없습니다.</p>'}
choiceBtns.forEach(btn=>btn.onclick=()=>{if(running)return;pick=btn.dataset.pick;choiceBtns.forEach(x=>x.classList.toggle('selected',x===btn));toss.disabled=false;guide.textContent=`${pick==='front'?'앞면':'뒷면'}을 선택했습니다.`});
function flip(){if(!pick||running)return;running=true;toss.disabled=true;choiceBtns.forEach(x=>x.disabled=true);guide.textContent='동전이 빠르게 회전합니다…';const side=fairSide(),start=performance.now(),from=angle,tau=Math.PI*2,current=((angle%tau)+tau)%tau,desired=side==='back'?Math.PI:0,delta=tau*(9+Math.floor(Math.random()*4))+((desired-current+tau)%tau),target=angle+delta,duration=3100;function frame(now){const t=Math.min(1,(now-start)/duration),p=1-Math.pow(1-t,4);angle=from+(target-from)*p;coin.style.transform=`translateY(${-Math.sin(t*Math.PI)*85}px) rotateY(${angle}rad) rotateZ(${Math.sin(t*Math.PI*2)*10}deg)`;if(t<1)requestAnimationFrame(frame);else finish(side)}requestAnimationFrame(frame)}
function finish(side){running=false;angle=((angle%(Math.PI*2))+Math.PI*2)%(Math.PI*2);coin.style.transform=`rotateY(${angle}rad)`;const win=pick===side;history.unshift({pick,side,win});history=history.slice(0,10);renderHistory();resultTitle.textContent=side==='front'?'앞면!':'뒷면!';resultText.textContent=win?'예측 성공 🎉':'예측 실패';resultText.style.color=win?'#ffe04c':'#a9c0d1';result.hidden=false;guide.textContent='결과가 나왔습니다.'}
function reset(){result.hidden=true;pick=null;choiceBtns.forEach(x=>{x.disabled=false;x.classList.remove('selected')});toss.disabled=true;guide.textContent='동전의 앞면과 뒷면 중 하나를 선택하세요.'}
toss.onclick=flip;again.onclick=reset;renderHistory();
