(()=>{"use strict";
const animals=[{emoji:"🐵",name:"원숭이",fur:"#98613e",trim:"#744128"},{emoji:"🐰",name:"토끼",fur:"#f1eee7",trim:"#d9d4ca"},{emoji:"🐯",name:"호랑이",fur:"#e7892e",trim:"#744128"},{emoji:"🐼",name:"판다",fur:"#efefed",trim:"#34383b"},{emoji:"🐻",name:"곰",fur:"#8d5b3b",trim:"#613c29"},{emoji:"🦊",name:"여우",fur:"#e8792d",trim:"#773e25"},{emoji:"🐱",name:"고양이",fur:"#87939d",trim:"#59636b"},{emoji:"🐧",name:"펭귄",fur:"#353c45",trim:"#f1f0e8"},{emoji:"🐶",name:"강아지",fur:"#a07b5a",trim:"#6d4d35"},{emoji:"🐸",name:"개구리",fur:"#57a95c",trim:"#33713d"},{emoji:"🐨",name:"코알라",fur:"#8b969d",trim:"#5d666c"},{emoji:"🦁",name:"사자",fur:"#c78b3e",trim:"#86552e"}];
const personalities=[{key:"attack",name:"공격형",attack:1.3,defense:1},{key:"defense",name:"방어형",attack:.9,defense:.62},{key:"balance",name:"균형형",attack:1,defense:.85}];
const countEl=document.querySelector("#playerCount"),inputsEl=document.querySelector("#nameInputs"),startButton=document.querySelector("#startButton"),arenaEl=document.querySelector("#arena"),platformEl=document.querySelector("#platform"),statusEl=document.querySelector("#status"),aliveEl=document.querySelector("#alive"),resultEl=document.querySelector("#result"),winnerAnimalEl=document.querySelector("#winnerAnimal"),winnerNameEl=document.querySelector("#winnerName"),againButton=document.querySelector("#againButton"),countdownEl=document.querySelector("#countdown");
let fighters=[],running=false,frameId=0,startTime=0,lastTime=0;
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char])}
function shuffle(values){const copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
for(let i=2;i<=12;i++){const option=document.createElement("option");option.value=i;option.textContent=`${i}명`;if(i===2)option.selected=true;countEl.append(option)}
function names(){return[...inputsEl.querySelectorAll("input")].map((input,i)=>input.value.trim()||`참가자 ${i+1}`)}
function renderInputs(){const count=Number(countEl.value),old=names();inputsEl.innerHTML="";for(let i=0;i<count;i++){const label=document.createElement("label");label.className="name-input";label.innerHTML=`<span>${animals[i].emoji}</span><input maxlength="8" value="${escapeHtml(old[i]||animals[i].name)}" aria-label="${i+1}번 참가자 이름">`;inputsEl.append(label)}aliveEl.textContent=count}
function createFighters(){arenaEl.querySelectorAll(".fighter").forEach(el=>el.remove());const size=arenaEl.clientWidth,center=size/2,radius=size*.28,list=names(),traits=shuffle(list.map((_,i)=>personalities[i%personalities.length]));fighters=list.map((name,i)=>{const angle=i/list.length*Math.PI*2,x=center+Math.cos(angle)*radius,y=center+Math.sin(angle)*radius,trait=traits[i],el=document.createElement("div");el.className="fighter walking";el.style.setProperty("--fur",animals[i].fur);el.style.setProperty("--trim",animals[i].trim);el.innerHTML=`<span class="avatar"><i class="body"></i><i class="arm arm-left"></i><i class="arm arm-right"></i><i class="leg leg-left"></i><i class="leg leg-right"></i><i class="head">${animals[i].emoji}</i></span><span class="tag ${trait.key}">${escapeHtml(name)}<b>${trait.name}</b></span><strong class="skill-label"></strong>`;arenaEl.append(el);return{name,animal:animals[i],trait,x,y,vx:(Math.random()-.5)*1.1,vy:(Math.random()-.5)*1.1,knockedUntil:0,attackCooldown:0,skillCooldown:0,alive:true,el}});aliveEl.textContent=fighters.length;renderPositions()}
function renderPositions(){const size=arenaEl.clientWidth,center=size/2;for(const f of fighters){const visualY=center+(f.y-center)*.72;f.el.style.transform=`translate(${f.x-f.el.offsetWidth/2}px,${visualY-f.el.offsetHeight/2}px)`;f.el.style.zIndex=String(10+Math.round(visualY))}}
function start(){if(running)return;resultEl.hidden=true;createFighters();running=true;startButton.disabled=true;countEl.disabled=true;inputsEl.querySelectorAll("input").forEach(x=>x.disabled=true);let count=3;countdownEl.hidden=false;countdownEl.textContent=count;statusEl.textContent="곧 대결이 시작됩니다.";const countdown=setInterval(()=>{count--;if(count>0){countdownEl.textContent=count;return}clearInterval(countdown);countdownEl.textContent="GO!";setTimeout(()=>countdownEl.hidden=true,500);startTime=performance.now();lastTime=startTime;statusEl.textContent="서로를 경기장 밖으로 밀어내세요!";frameId=requestAnimationFrame(tick)},650)}
function tick(now){if(!running||!startTime)return;const dt=Math.min(2,(now-lastTime)/16.67),last=fighters.filter(f=>f.alive),size=arenaEl.clientWidth,center=size/2,radius=size*.42;lastTime=now;
  for(const f of last){const edgeDistance=Math.hypot(f.x-center,f.y-center),enemies=last.filter(other=>other!==f);f.vx+=(Math.random()-.5)*.1*dt;f.vy+=(Math.random()-.5)*.1*dt;if(f.trait.key==="attack"&&enemies.length){const target=enemies.reduce((best,enemy)=>Math.hypot(enemy.x-f.x,enemy.y-f.y)<Math.hypot(best.x-f.x,best.y-f.y)?enemy:best),dx=target.x-f.x,dy=target.y-f.y,d=Math.hypot(dx,dy)||1;f.vx+=dx/d*.075*dt;f.vy+=dy/d*.075*dt}else if(f.trait.key==="defense"){f.vx+=(center-f.x)*.0045*dt;f.vy+=(center-f.y)*.0045*dt;const threat=enemies.find(enemy=>Math.hypot(enemy.x-f.x,enemy.y-f.y)<75);if(threat){f.vx+=(f.x-threat.x)*.004*dt;f.vy+=(f.y-threat.y)*.004*dt}}if(edgeDistance>radius*.7&&f.knockedUntil<now){f.vx+=(center-f.x)*.0032*dt;f.vy+=(center-f.y)*.0032*dt}const speed=Math.hypot(f.vx,f.vy)||1,max=f.trait.key==="attack"?2.35:2.05;if(speed>max){f.vx=f.vx/speed*max;f.vy=f.vy/speed*max}f.x+=f.vx*dt;f.y+=f.vy*dt}
  for(let i=0;i<last.length;i++)for(let j=i+1;j<last.length;j++){const a=last[i],b=last[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;if(d<42){const nx=dx/d,ny=dy/d,overlap=(42-d)*.08;a.x-=nx*overlap;b.x+=nx*overlap;a.y-=ny*overlap;b.y+=ny*overlap;if(a.attackCooldown>now||b.attackCooldown>now)continue;const attacker=a.trait.key==="attack"&&b.trait.key!=="attack"?a:b.trait.key==="attack"&&a.trait.key!=="attack"?b:Math.random()<.5?a:b,victim=attacker===a?b:a,direction=attacker===a?1:-1,ultimate=Math.random()<.025&&attacker.skillCooldown<now&&victim.skillCooldown<now,basePower=ultimate?4.8:(Math.random()<.14?2.8:.95),power=basePower*attacker.trait.attack*victim.trait.defense;victim.vx+=nx*direction*power;victim.vy+=ny*direction*power;victim.knockedUntil=now+(ultimate?1250:850);attacker.attackCooldown=now+(attacker.trait.key==="attack"?420:620);victim.attackCooldown=now+280;attacker.el.classList.add(ultimate?"ultimate":"punching");victim.el.classList.add("hit");if(ultimate){attacker.skillCooldown=now+5000;victim.skillCooldown=now+2500;attacker.el.querySelector(".skill-label").textContent="🔥 필살기!";arenaEl.classList.add("ultimate-wave");statusEl.textContent=`${attacker.name} 필살기 발동!`}setTimeout(()=>{attacker.el.classList.remove("ultimate","punching");victim.el.classList.remove("hit");attacker.el.querySelector(".skill-label").textContent="";arenaEl.classList.remove("ultimate-wave")},ultimate?700:300)}}
  const knockouts=[];for(const f of last){const dx=f.x-center,dy=f.y-center,d=Math.hypot(dx,dy)||1;if(d>radius+16&&f.knockedUntil>now){knockouts.push({fighter:f,distance:d})}else if(d>radius&&f.knockedUntil<=now){f.x=center+dx/d*(radius-3);f.y=center+dy/d*(radius-3);f.vx=-dx/d*.9;f.vy=-dy/d*.9}}knockouts.sort((a,b)=>b.distance-a.distance);for(const item of knockouts.slice(0,Math.max(0,last.length-1))){item.fighter.alive=false;item.fighter.el.classList.add("out")}
  const alive=fighters.filter(f=>f.alive);aliveEl.textContent=alive.length;renderPositions();if(alive.length<=1){finish(alive[0]||last[Math.floor(Math.random()*last.length)]);return}frameId=requestAnimationFrame(tick)}
function finish(winner){running=false;cancelAnimationFrame(frameId);startButton.disabled=false;countEl.disabled=false;inputsEl.querySelectorAll("input").forEach(x=>x.disabled=false);statusEl.textContent=`${winner.name} 최후의 생존!`;winnerAnimalEl.textContent=winner.animal.emoji;winnerNameEl.textContent=`${winner.name} 승리!`;resultEl.hidden=false}
function reset(){resultEl.hidden=true;statusEl.textContent="참가자를 설정하세요.";createFighters()}
countEl.addEventListener("change",renderInputs);startButton.addEventListener("click",start);againButton.addEventListener("click",reset);renderInputs();requestAnimationFrame(createFighters);
})();
