import * as THREE from '../vendor/three.module.min.js';
import { GLTFLoader } from '../vendor/loaders/GLTFLoader.js';
document.querySelector('#status').textContent='3D 엔진 시작…';
const host=document.querySelector('#canvas'),statusEl=document.querySelector('#status'),aliveEl=document.querySelector('#alive'),countdown=document.querySelector('#countdown'),traitsEl=document.querySelector('#traits'),events=document.querySelector('#events');
const startBtn=document.querySelector('#start'),againBtn=document.querySelector('#again'),result=document.querySelector('#result'),winner=document.querySelector('#winner');
const scene=new THREE.Scene();scene.background=new THREE.Color(0xc98250);scene.fog=new THREE.Fog(0xc98250,18,42);const camera=new THREE.PerspectiveCamera(48,1,.1,80);camera.position.set(0,10,14);camera.lookAt(0,0,0);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.shadowMap.enabled=true;host.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffe5bd,0x5c3829,2.2));const sun=new THREE.DirectionalLight(0xffe6b5,3.2);sun.position.set(-10,18,10);sun.castShadow=true;scene.add(sun);
const clock=new THREE.Clock(),loader=new GLTFLoader(),radius=5.7;let fighters=[],effects=[],running=false;
function add(g,m,x,y,z){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;scene.add(o);return o}
add(new THREE.CylinderGeometry(6.2,6.5,.65,48),new THREE.MeshStandardMaterial({color:0xc58a58,roughness:1}),0,-.32,0);add(new THREE.CylinderGeometry(5.72,5.95,.1,48),new THREE.MeshStandardMaterial({color:0xe0aa70,roughness:1}),0,.05,0);
for(let i=0;i<28;i++){const a=i/28*Math.PI*2,x=Math.cos(a)*8.2,z=Math.sin(a)*8.2;const c=[0xf36d60,0x4fb3db,0xf0ca42,0x73bc71][i%4];add(new THREE.SphereGeometry(.32,8,7),new THREE.MeshStandardMaterial({color:c}),x,.8,z);add(new THREE.CylinderGeometry(.24,.3,.75,7),new THREE.MeshStandardMaterial({color:c}),x,.25,z)}
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function normalize(model){const b=new THREE.Box3().setFromObject(model),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3());model.position.sub(c);model.position.y+=s.y/2;model.scale.setScalar(1.8/Math.max(s.y,.01));model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}})}
function getClip(f,words){return f.clips.find(c=>words.some(w=>c.name.toLowerCase().includes(w)))||f.clips[0]}function play(f,words,once=false){const c=getClip(f,words);if(!c||f.action?.getClip()===c)return;const a=f.mixer.clipAction(c);a.reset().setLoop(once?THREE.LoopOnce:THREE.LoopRepeat,once?1:Infinity);a.clampWhenFinished=once;a.fadeIn(.1).play();f.action?.fadeOut(.1);f.action=a}
async function load(){const specs=[['토끼','models/bunny.glb'],['몽구스','models/monkroose.glb']];fighters=await Promise.all(specs.map(async(s,i)=>{const g=await loader.loadAsync(s[1]);normalize(g.scene);scene.add(g.scene);const f={name:s[0],root:g.scene,clips:g.animations,mixer:new THREE.AnimationMixer(g.scene),action:null,vel:new THREE.Vector3(),trait:'공격형',cool:1,hp:0,out:false,fall:0,ultimate:false};play(f,['idle']);return f}));reset();statusEl.textContent='준비 완료'}
function announce(t){const s=document.createElement('span');s.textContent=t;events.prepend(s);setTimeout(()=>s.remove(),2100)}function burst(pos,big=false){for(let i=0;i<(big?30:12);i++){const o=add(new THREE.SphereGeometry(big?.09:.055,5,5),new THREE.MeshBasicMaterial({color:i%2?0xffffff:0xffdf38}),pos.x,1.1,pos.z);effects.push({o,v:new THREE.Vector3((Math.random()-.5)*(big?10:6),Math.random()*(big?8:5),(Math.random()-.5)*(big?10:6)),life:big?1:.55})}}
function reset(){running=false;result.hidden=true;againBtn.hidden=true;events.innerHTML='';const types=['공격형','방어형','균형형'];fighters.forEach((f,i)=>{f.name=document.querySelector(`#name${i}`).value||['토끼','몽구스'][i];f.root.position.set(i?-2.6:2.6,0,(Math.random()-.5)*1.3);f.root.rotation.set(0,i?-Math.PI/2:Math.PI/2,0);f.vel.set(0,0,0);f.trait=types[Math.floor(Math.random()*types.length)];f.cool=.5+Math.random();f.hp=0;f.out=false;f.fall=0;f.ultimate=false;play(f,['idle'])});traitsEl.innerHTML=fighters.map(f=>`<div><b>${f.name}</b> · ${f.trait}</div>`).join('');aliveEl.textContent='2'}
async function start(){reset();startBtn.disabled=true;for(const v of ['3','2','1','FIGHT!']){countdown.textContent=v;await new Promise(r=>setTimeout(r,v==='FIGHT!'?650:700))}countdown.textContent='';running=true;statusEl.textContent='대결 중';fighters.forEach(f=>play(f,['run','walk']))}
function hit(a,b){const d=new THREE.Vector3().subVectors(b.root.position,a.root.position).setY(0).normalize();const edge=b.root.position.length()/radius;const defense=b.trait==='방어형'?.72:1;const ultimate=Math.random()<.09&&!a.ultimate;a.ultimate||=ultimate;b.hp+=ultimate?2:1;const power=(ultimate?5.4:2.05+Math.random()*.85)*(1+b.hp*.16)*(1+edge*.35)*defense;b.vel.addScaledVector(d,power);a.vel.addScaledVector(d,-.18);play(a,['punch','attack'],true);play(b,['hit'],true);burst(b.root.position,ultimate);announce(ultimate?`${a.name} 필살기! 강한 넉백`:`${a.name}의 공격!`);a.cool=ultimate?2.5:1+Math.random()*.8;b.cool=.65}
function update(dt){const alive=fighters.filter(f=>!f.out);for(const f of alive){const target=alive.find(x=>x!==f);if(!target)continue;f.cool-=dt;const to=new THREE.Vector3().subVectors(target.root.position,f.root.position);to.y=0;const dist=to.length();to.normalize();const desired=f.trait==='공격형'?2.35:f.trait==='방어형'?1.35:1.8;if(dist>1.15){f.root.position.addScaledVector(to,desired*dt);play(f,['run','walk'])}else if(f.cool<=0)hit(f,target);else play(f,['idle']);f.root.rotation.y=Math.atan2(to.x,to.z);f.root.position.addScaledVector(f.vel,dt);f.vel.multiplyScalar(Math.pow(.14,dt));
  const r=Math.hypot(f.root.position.x,f.root.position.z);if(r>radius){f.out=true;f.fall=0;f.vel.multiplyScalar(.6);play(f,['death'],true);announce(`${f.name} 링 아웃!`)}}
 for(const f of fighters.filter(x=>x.out)){f.fall+=dt;f.root.position.addScaledVector(f.vel,dt);f.root.position.y-=dt*(.7+f.fall*4);f.root.rotation.z+=dt*2.2}
 aliveEl.textContent=fighters.filter(f=>!f.out).length;if(fighters.filter(f=>!f.out).length===1){running=false;const win=fighters.find(f=>!f.out);statusEl.textContent='대결 종료';winner.textContent=`🏆 ${win.name} 승리`;result.hidden=false;againBtn.hidden=false;startBtn.disabled=false;play(win,['wave','yes','idle'])}}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);fighters.forEach(f=>f.mixer.update(dt));effects.forEach((e,i)=>{e.life-=dt;e.o.position.addScaledVector(e.v,dt);e.v.y-=8*dt;e.o.scale.setScalar(Math.max(0,e.life));if(e.life<=0){scene.remove(e.o);effects.splice(i,1)}});if(running)update(dt);renderer.render(scene,camera)}
startBtn.onclick=start;againBtn.onclick=start;load().then(animate).catch(e=>{statusEl.textContent='3D 모델 로딩 실패';console.error(e)});
