(()=>{"use strict";
const animals=["🐵","🐰","🐯","🐼","🐻","🦊","🐱","🐧","🐶","🐸","🐨","🦁","🐮","🐷","🐹","🐔","🐺","🦄","🐙","🦖"],defaults=["원숭이","토끼","호랑이","판다","곰","여우","고양이","펭귄","강아지","개구리","코알라","사자"];
const countEl=document.querySelector("#playerCount"),inputsEl=document.querySelector("#nameInputs"),startButton=document.querySelector("#startButton"),arenaEl=document.querySelector("#arena"),platformEl=document.querySelector("#platform"),statusEl=document.querySelector("#status"),aliveEl=document.querySelector("#alive"),resultEl=document.querySelector("#result"),winnerAnimalEl=document.querySelector("#winnerAnimal"),winnerNameEl=document.querySelector("#winnerName"),againButton=document.querySelector("#againButton");
let fighters=[],running=false,frameId=0,startTime=0,lastTime=0;
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char])}
for(let i=2;i<=12;i++){const option=document.createElement("option");option.value=i;option.textContent=`${i}명`;if(i===8)option.selected=true;countEl.append(option)}
function names(){return[...inputsEl.querySelectorAll("input")].map((input,i)=>input.value.trim()||`참가자 ${i+1}`)}
function renderInputs(){const count=Number(countEl.value),old=names();inputsEl.innerHTML="";for(let i=0;i<count;i++){const label=document.createElement("label");label.className="name-input";label.innerHTML=`<span>${animals[i]}</span><input maxlength="8" value="${escapeHtml(old[i]||defaults[i]||`참가자 ${i+1}`)}" aria-label="${i+1}번 참가자 이름">`;inputsEl.append(label)}aliveEl.textContent=count}
function createFighters(){arenaEl.querySelectorAll(".fighter").forEach(el=>el.remove());const size=arenaEl.clientWidth,center=size/2,radius=size*.28,list=names();fighters=list.map((name,i)=>{const angle=i/list.length*Math.PI*2,x=center+Math.cos(angle)*radius,y=center+Math.sin(angle)*radius,el=document.createElement("div");el.className="fighter";el.innerHTML=`${animals[i]}<span class="tag">${escapeHtml(name)}</span>`;arenaEl.append(el);return{name,animal:animals[i],x,y,vx:(Math.random()-.5)*1.4,vy:(Math.random()-.5)*1.4,alive:true,el}});aliveEl.textContent=fighters.length;renderPositions()}
function renderPositions(){for(const f of fighters)f.el.style.transform=`translate(${f.x-f.el.offsetWidth/2}px,${f.y-f.el.offsetHeight/2}px)`}
function start(){if(running)return;resultEl.hidden=true;createFighters();running=true;startButton.disabled=true;countEl.disabled=true;inputsEl.querySelectorAll("input").forEach(x=>x.disabled=true);statusEl.textContent="플랫폼이 점점 좁아집니다!";startTime=performance.now();lastTime=startTime;frameId=requestAnimationFrame(tick)}
function tick(now){if(!running)return;const dt=Math.min(2,(now-lastTime)/16.67),elapsed=now-startTime,last= fighters.filter(f=>f.alive),size=arenaEl.clientWidth,center=size/2,shrink=Math.min(.5,elapsed/40000*.5),radius=size*(.42-shrink*.42);lastTime=now;platformEl.style.width=`${86-shrink*84}%`;platformEl.style.height=`${86-shrink*84}%`;
  for(const f of last){f.vx+=(Math.random()-.5)*.16*dt;f.vy+=(Math.random()-.5)*.16*dt;const speed=Math.hypot(f.vx,f.vy)||1,max=2.4;if(speed>max){f.vx=f.vx/speed*max;f.vy=f.vy/speed*max}f.x+=f.vx*dt;f.y+=f.vy*dt}
  for(let i=0;i<last.length;i++)for(let j=i+1;j<last.length;j++){const a=last[i],b=last[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||1;if(d<38){const power=Math.random()<.045?4.6:1.25,nx=dx/d,ny=dy/d;a.vx-=nx*power;a.vy-=ny*power;b.vx+=nx*power;b.vy+=ny*power;if(power>4){a.el.classList.add("hit");b.el.classList.add("hit");setTimeout(()=>{a.el.classList.remove("hit");b.el.classList.remove("hit")},190)}}}
  for(const f of last){if(Math.hypot(f.x-center,f.y-center)>radius){f.alive=false;f.el.classList.add("out")}}
  const alive=fighters.filter(f=>f.alive);aliveEl.textContent=alive.length;renderPositions();if(alive.length<=1){finish(alive[0]||last[Math.floor(Math.random()*last.length)]);return}frameId=requestAnimationFrame(tick)}
function finish(winner){running=false;cancelAnimationFrame(frameId);startButton.disabled=false;countEl.disabled=false;inputsEl.querySelectorAll("input").forEach(x=>x.disabled=false);statusEl.textContent=`${winner.name} 최후의 생존!`;winnerAnimalEl.textContent=winner.animal;winnerNameEl.textContent=`${winner.name} 승리!`;resultEl.hidden=false}
function reset(){resultEl.hidden=true;platformEl.style.width="86%";platformEl.style.height="86%";statusEl.textContent="참가자를 설정하세요.";createFighters()}
countEl.addEventListener("change",renderInputs);startButton.addEventListener("click",start);againButton.addEventListener("click",reset);renderInputs();requestAnimationFrame(createFighters);
})();
