const $=s=>document.querySelector(s);
const host=$('#canvas'),stage=$('.stage'),statusEl=$('#status'),aliveEl=$('#alive'),countdown=$('#countdown'),events=$('#events');
const countEl=$('#playerCount'),namesEl=$('#names'),lineupEl=$('#lineup'),intro=$('#intro'),startBtn=$('#start'),againBtn=$('#again');
const resultEl=$('#results'),winnerEl=$('#winner'),finishText=$('#finishText'),standingEl=$('#standing'),soundBtn=$('#soundToggle');
const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');host.append(canvas);
const animals=[['토끼','🐰','rabbit'],['원숭이','🐵','monkey'],['고양이','🐱','cat'],['닭','🐔','chicken'],['판다','🐼','panda'],['여우','🦊','fox'],['강아지','🐶','puppy'],['호랑이','🐯','tiger']];
let W=960,H=720,dpr=1,ready=false,running=false,last=performance.now(),startedAt=0,fighters=[],effects=[],sprites=[],placements=[],soundOn=true,audio;

function resize(){const r=host.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,1.5);W=Math.max(620,r.width);H=Math.max(560,r.height);canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true}
addEventListener('resize',resize);resize();
const arena=()=>({cx:W*.53,cy:H*.55,rx:Math.min(W*.38,390),ry:Math.min(H*.31,210)});

function removeChecker(img){const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);const im=x.getImageData(0,0,c.width,c.height),d=im.data,w=c.width,h=c.height,seen=new Uint8Array(w*h),q=new Int32Array(w*h);let head=0,tail=0;const bg=p=>{const i=p*4,r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b);return mx>198&&mx-mn<18};const add=p=>{if(p>=0&&p<w*h&&!seen[p]&&bg(p)){seen[p]=1;q[tail++]=p}};for(let i=0;i<w;i++){add(i);add((h-1)*w+i)}for(let y=0;y<h;y++){add(y*w);add(y*w+w-1)}while(head<tail){const p=q[head++],px=p%w;d[p*4+3]=0;if(px)add(p-1);if(px<w-1)add(p+1);add(p-w);add(p+w)}x.putImageData(im,0,0);return c}
function isolateFrame(sheet,index){const sw=Math.floor(sheet.width/6),sh=sheet.height,sx=index*sw,c=document.createElement('canvas');c.width=sw;c.height=sh;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(sheet,sx,0,sw,sh,0,0,sw,sh);const im=x.getImageData(0,0,sw,sh),d=im.data,n=sw*sh,lab=new Uint16Array(n),q=new Int32Array(n);let id=0,best=0,bestN=0;for(let p=0;p<n;p++){if(lab[p]||d[p*4+3]<24)continue;id++;let h=0,t=0,size=0;lab[p]=id;q[t++]=p;while(h<t){const z=q[h++],zx=z%sw;size++;const add=v=>{if(v>=0&&v<n&&!lab[v]&&d[v*4+3]>=24){lab[v]=id;q[t++]=v}};if(zx)add(z-1);if(zx<sw-1)add(z+1);add(z-sw);add(z+sw)}if(size>bestN){bestN=size;best=id}}let minX=sw,minY=sh,maxX=0,maxY=0;for(let p=0;p<n;p++){if(lab[p]!==best)d[p*4+3]=0;else{const px=p%sw,py=p/sw|0;minX=Math.min(minX,px);maxX=Math.max(maxX,px);minY=Math.min(minY,py);maxY=Math.max(maxY,py)}}x.putImageData(im,0,0);const pad=4,t=document.createElement('canvas');t.width=Math.max(1,maxX-minX+1+pad*2);t.height=Math.max(1,maxY-minY+1+pad*2);t.getContext('2d').drawImage(c,minX,minY,maxX-minX+1,maxY-minY+1,pad,pad,maxX-minX+1,maxY-minY+1);return t}
const loadImage=src=>new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src});
async function loadSprites(){const imgs=await Promise.all(animals.map(a=>loadImage(`assets/${a[2]}-cycle.png?v=1`)));sprites=imgs.map(img=>{const clean=removeChecker(img);return Array.from({length:6},(_,i)=>isolateFrame(clean,i))});ready=true;statusEl.textContent='준비 완료'}

function rebuildInputs(){const n=+countEl.value,old=[...namesEl.querySelectorAll('input')].map(x=>x.value);namesEl.innerHTML='';for(let i=0;i<n;i++){const l=document.createElement('label');l.innerHTML=`<span>${animals[i][1]} ${i+1}</span><input value="${old[i]||animals[i][0]}">`;l.querySelector('input').oninput=rebuildLineup;namesEl.append(l)}rebuildLineup();intro.hidden=false;resetBattle()}
function rebuildLineup(){lineupEl.innerHTML=[...namesEl.querySelectorAll('input')].map((x,i)=>`<div><span>${animals[i][1]}</span><b>${x.value||animals[i][0]}</b></div>`).join('')}
countEl.onchange=rebuildInputs;
function announce(t){const s=document.createElement('span');s.textContent=t;events.prepend(s);setTimeout(()=>s.remove(),1900)}

function resetBattle(){running=false;placements=[];effects=[];resultEl.hidden=true;events.innerHTML='';const a=arena(),inputs=[...namesEl.querySelectorAll('input')],n=inputs.length,rowCount=Math.ceil(n/2);fighters=inputs.map((x,i)=>{const side=i%2===0?-1:1,row=Math.floor(i/2),rowGap=n<=2?0:Math.min(48,a.ry*1.15/Math.max(1,rowCount-1)),y=a.cy+(row-(rowCount-1)/2)*rowGap;return{i,name:x.value||animals[i][0],x:a.cx+side*a.rx*.67,y,homeY:y,vx:0,vy:0,hp:100,maxHp:100,phase:Math.random()*4,face:side<0?1:-1,state:'idle',stateT:0,cool:.45+Math.random(),special:0,target:null,alive:true,guard:0,stun:0,flash:0,scale:1,defeatedBy:''}});aliveEl.textContent=n;statusEl.textContent=ready?'준비 완료':'이미지 준비 중'}

function ensureAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}
function tone(freq,dur,type='square',vol=.035,slide=0){if(!soundOn)return;ensureAudio();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(40,freq+slide),audio.currentTime+dur);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function sfx(kind){if(kind==='hit'){tone(125,.07,'square',.045,-50);setTimeout(()=>tone(80,.06,'sawtooth',.025),25)}else if(kind==='special'){tone(210,.2,'sawtooth',.04,500);setTimeout(()=>tone(610,.18,'square',.035,-250),110)}else if(kind==='out'){tone(170,.4,'sawtooth',.04,-120)}else if(kind==='ko'){tone(95,.55,'square',.045,-45)}else if(kind==='start'){tone(420,.1,'square',.035,130)}}
soundBtn.onclick=()=>{soundOn=!soundOn;soundBtn.textContent=soundOn?'🔊 사운드 켜짐':'🔇 사운드 꺼짐';if(soundOn)ensureAudio()};

function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function pickTarget(f){let list=fighters.filter(o=>o.alive&&o!==f);list.sort((a,b)=>(Math.abs(f.y-a.y)*2+Math.abs(f.x-a.x))-(Math.abs(f.y-b.y)*2+Math.abs(f.x-b.x)));return list[0]||null}
function inside(f,margin=0){const a=arena(),dx=(f.x-a.cx)/(a.rx-margin),dy=(f.y-a.cy)/(a.ry-margin);return dx*dx+dy*dy<=1}
function nearestEdge(f){const a=arena(),dx=f.x-a.cx,dy=f.y-a.cy,q=1/Math.sqrt((dx*dx)/(a.rx*a.rx)+(dy*dy)/(a.ry*a.ry)||1);return{x:a.cx+dx*q,y:a.cy+dy*q}}
function impact(x,y,color='#fff343',big=false){effects.push({kind:'impact',x,y,life:big?.55:.3,max:big?.55:.3,color,big});stage.classList.remove(big?'impact':'ultimate');void stage.offsetWidth;stage.classList.add(big?'ultimate':'impact');setTimeout(()=>stage.classList.remove('impact','ultimate'),big?560:220)}

function attack(f){const t=f.target;if(!t?.alive)return;const special=f.special>=100;f.state=special?'special':'attack';f.stateT=special?.72:.38;f.cool=special?2.1:.65+Math.random()*.4;f.didHit=false;if(special){f.special=0;announce(`⚡ ${f.name} 필살기!`);sfx('special')}}
function resolveHit(f){const t=f.target;if(!t?.alive||Math.abs(f.x-t.x)>92||Math.abs(f.y-t.y)>165)return;const special=f.state==='special',guarding=t.guard>0;let damage=(special?30:8+Math.random()*7)*(guarding?.38:1),power=(special?340:105+Math.random()*55)*(guarding?.42:1);t.hp=Math.max(0,t.hp-damage);t.stun=special?.65:.22;t.flash=.16;f.special=Math.min(100,f.special+(special?0:18));t.special=Math.min(100,t.special+10);const direction=t.x>=f.x?1:-1;t.vx+=direction*power;t.vy=0;impact(t.x,t.y-25,special?'#5cf4ff':'#ffe83b',special);if(!special)sfx('hit');if(t.hp<=0)defeat(t,f,'KO')}
function defeat(f,by,reason){if(!f.alive)return;f.alive=false;f.state=reason==='장외'?'fall':'ko';f.stateT=2;f.defeatedBy=by?.name||'';placements.unshift(f);aliveEl.textContent=fighters.filter(x=>x.alive).length;announce(`${reason==='KO'?'💫':'🌪️'} ${f.name} ${reason}!`);sfx(reason==='KO'?'ko':'out');if(fighters.filter(x=>x.alive).length<=1)setTimeout(finish,900)}

function update(dt){const a=arena();for(const f of fighters){f.flash=Math.max(0,f.flash-dt);if(!f.alive){f.stateT-=dt;f.vy+=260*dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.scale=Math.max(.15,f.scale-dt*.75);continue}f.phase+=dt*9;f.cool-=dt;f.stun=Math.max(0,f.stun-dt);f.guard=Math.max(0,f.guard-dt);if(f.stateT>0){f.stateT-=dt;if((f.state==='attack'||f.state==='special')&&!f.didHit&&f.stateT<(f.state==='special'?.31:.15)){f.didHit=true;resolveHit(f)}if(f.stateT<=0)f.state='idle'}f.x+=f.vx*dt;f.y=f.homeY;f.vy=0;f.vx*=Math.pow(.07,dt);if(f.stun>0)continue;
    f.target=pickTarget(f);if(!f.target)continue;const dx=f.target.x-f.x,xGap=Math.abs(dx);f.face=dx>=0?1:-1;
    if(f.state==='idle'){if(xGap>65){f.state='move';const speed=82+(f.i%3)*6;f.x+=Math.sign(dx)*speed*dt}else if(f.cool<=0)attack(f);else if(Math.random()<dt*.32){f.guard=.4;f.state='guard';f.stateT=.4}}
    else if(f.state==='move'){if(xGap<68)f.state='idle';else{const speed=88+(f.i%3)*5;f.x+=Math.sign(dx)*speed*dt}}
    const edgeDistance=Math.abs(f.x-a.cx)-a.rx;if(edgeDistance>30)defeat(f,f.target,'장외');else if(edgeDistance>-8&&Math.abs(f.vx)<55)f.x+=Math.sign(a.cx-f.x)*34*dt;
  }
  for(let i=effects.length-1;i>=0;i--){effects[i].life-=dt;if(effects[i].life<=0)effects.splice(i,1)}
  if(performance.now()-startedAt>45000&&fighters.filter(f=>f.alive).length>1){const living=fighters.filter(f=>f.alive).sort((x,y)=>x.hp-y.hp);defeat(living[0],living.at(-1),'KO')}
}

function roundRect(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill()}
function drawArena(){const a=arena(),g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#173e58');g.addColorStop(.55,'#42788a');g.addColorStop(1,'#08131e');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<22;i++){ctx.fillStyle=i%2?'#173148':'#1b3c53';ctx.fillRect(i*W/22,H*.13,W/22+1,H*.25)}ctx.save();ctx.translate(a.cx,a.cy+26);ctx.scale(1,.48);ctx.fillStyle='#0008';ctx.beginPath();ctx.arc(0,0,a.rx+34,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(a.cx,a.cy);ctx.scale(1,a.ry/a.rx);const floor=ctx.createRadialGradient(-a.rx*.22,-a.rx*.22,10,0,0,a.rx);floor.addColorStop(0,'#eef3da');floor.addColorStop(.7,'#b8c6ad');floor.addColorStop(1,'#71857b');ctx.fillStyle=floor;ctx.beginPath();ctx.arc(0,0,a.rx,0,Math.PI*2);ctx.fill();ctx.lineWidth=18;ctx.strokeStyle='#394e52';ctx.stroke();ctx.lineWidth=3;ctx.strokeStyle='#f5df65';ctx.stroke();ctx.restore();ctx.fillStyle='#fff6';ctx.font='900 44px DM Mono';ctx.textAlign='center';ctx.fillText('SGRA 88',a.cx,a.cy+14);ctx.textAlign='left'}
function drawFighter(f){const sprite=sprites[f.i]?.[f.state==='attack'||f.state==='special'?(f.stateT>(f.state==='special'?.31:.15)?4:5):Math.floor(f.phase)%4];if(!sprite)return;const depth=.82+(f.y-(arena().cy-arena().ry))/(arena().ry*2)*.34,size=78*depth*f.scale,ratio=sprite.width/sprite.height,bob=f.alive&&f.state==='move'?Math.abs(Math.sin(f.phase*Math.PI))*3:0;ctx.save();ctx.translate(f.x,f.y);ctx.scale(1,.35);ctx.fillStyle='#0005';ctx.beginPath();ctx.ellipse(0,14,27*depth,13*depth,0,0,Math.PI*2);ctx.fill();ctx.restore();ctx.save();ctx.translate(f.x,f.y-bob);ctx.scale(f.face,1);if(f.state==='special'){ctx.shadowColor='#5cf4ff';ctx.shadowBlur=28}if(f.flash){ctx.globalAlpha=.42;ctx.filter='brightness(3)'}ctx.drawImage(sprite,-size*ratio/2,-size,size*ratio,size);ctx.restore();if(!f.alive)return;const barW=58,x=f.x-barW/2,y=f.y-size-13;roundRect(x,y,barW,6,3,'#14212b');roundRect(x+1,y+1,(barW-2)*f.hp/f.maxHp,4,2,f.hp>45?'#45e676':'#ff4c55');ctx.fillStyle='#fff';ctx.font='900 10px sans-serif';ctx.textAlign='center';ctx.fillText(f.name,f.x,y-5);ctx.textAlign='left';if(f.special>=100){ctx.fillStyle='#56efff';ctx.fillRect(x,y+8,barW,3)}}
function drawEffects(){for(const e of effects){const p=e.life/e.max,r=(1-p)*(e.big?65:32);ctx.save();ctx.globalAlpha=p;ctx.strokeStyle=e.color;ctx.lineWidth=e.big?8:5;for(let k=0;k<8;k++){const an=k*Math.PI/4;ctx.beginPath();ctx.moveTo(e.x+Math.cos(an)*r*.3,e.y+Math.sin(an)*r*.3);ctx.lineTo(e.x+Math.cos(an)*r,e.y+Math.sin(an)*r);ctx.stroke()}ctx.restore()}}
function render(){drawArena();[...fighters].sort((a,b)=>a.y-b.y).forEach(drawFighter);drawEffects()}

function finish(){if(!running)return;running=false;const winner=fighters.find(f=>f.alive);if(!winner)return;placements.unshift(winner);statusEl.textContent='대결 종료';winnerEl.textContent=`🏆 ${winner.name} 우승`;finishText.textContent=`${((performance.now()-startedAt)/1000).toFixed(1)}초 · 마지막 생존`;standingEl.innerHTML=placements.map((f,i)=>`<li><b>${f.name}</b>${i?' — '+(f.defeatedBy?f.defeatedBy+'에게 패배':'탈락'):''}</li>`).join('');resultEl.hidden=false;startBtn.disabled=false;tone(392,.15,'square',.04,130);setTimeout(()=>tone(523,.3,'square',.04,180),150)}
async function start(){if(!ready)return;ensureAudio();intro.hidden=true;resetBattle();startBtn.disabled=true;for(const v of ['3','2','1','FIGHT!']){countdown.textContent=v;sfx('start');await new Promise(r=>setTimeout(r,v==='FIGHT!'?550:460))}countdown.textContent='';startedAt=performance.now();running=true;statusEl.textContent='격투 중'}
startBtn.onclick=start;againBtn.onclick=start;
function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.04);last=now;if(running)update(dt);render()}
rebuildInputs();loadSprites().then(()=>{resetBattle();requestAnimationFrame(loop)}).catch(e=>{statusEl.textContent='동물 애니메이션 로딩 실패';console.error(e)});
