(()=>{'use strict';
const canvas=document.querySelector('#raceCanvas'),ctx=canvas.getContext('2d'),picker=document.querySelector('#ballPicker'),ranking=document.querySelector('#ranking'),startButton=document.querySelector('#startButton'),resetButton=document.querySelector('#resetButton'),selectedCount=document.querySelector('#selectedCount'),selectedNames=document.querySelector('#selectedNames'),finishCount=document.querySelector('#finishCount'),finishTotal=finishCount.nextElementSibling,raceState=document.querySelector('#raceState'),errorBox=document.querySelector('#error'),countdown=document.querySelector('#countdown');
const W=220,H=1200,R=9,finishY=1140;
const palette=[{id:'red',name:'빨강',color:'#ef4035'},{id:'orange',name:'주황',color:'#ff8a27'},{id:'yellow',name:'노랑',color:'#f5cf33'},{id:'green',name:'초록',color:'#38a55a'},{id:'blue',name:'파랑',color:'#3184e6'},{id:'indigo',name:'남색',color:'#3f51a3'},{id:'violet',name:'보라',color:'#9b4bc5'}];
const leftWall=[{x:18,y:55},{x:18,y:215},{x:50,y:280},{x:18,y:350},{x:18,y:505},{x:54,y:555},{x:18,y:625},{x:18,y:790},{x:48,y:835},{x:48,y:1080},{x:82,y:1130},{x:82,y:1180}],rightWall=leftWall.map(point=>({x:W-point.x,y:point.y}));
function boundaryX(wall,y){if(y<=wall[0].y)return wall[0].x;for(let i=1;i<wall.length;i++){if(y<=wall[i].y){const a=wall[i-1],b=wall[i],t=(y-a.y)/(b.y-a.y);return a.x+(b.x-a.x)*t}}return wall.at(-1).x}
const pins=[];for(let row=0;row<13;row++){const y=165+row*72,offset=row%2?28:18;for(let x=offset;x<W-12;x+=44){if(x>boundaryX(leftWall,y)+12&&x<boundaryX(rightWall,y)-12)pins.push({x,y,r:4+(row%4===0?1:0)})}}
const bumpers=[{x:62,y:410,r:16},{x:158,y:410,r:16},{x:110,y:590,r:19},{x:62,y:780,r:15},{x:158,y:780,r:15}];
const rotors=[{cx:65,cy:315,length:68,startAngle:.12,speed:1.35},{cx:155,cy:375,length:68,startAngle:-.12,speed:-1.35},{cx:110,cy:535,length:82,startAngle:.7,speed:1.2},{cx:65,cy:720,length:68,startAngle:.12,speed:-1.45},{cx:155,cy:915,length:68,startAngle:-.12,speed:1.45}];rotors.forEach(rotor=>rotor.angle=rotor.startAngle);
let selected=new Set(),balls=[],results=[],running=false,raf=0,lastTime=0,startAt=0;
function renderPicker(){picker.textContent='';palette.forEach(ball=>{const button=document.createElement('button');button.type='button';button.className=`ball-option${selected.has(ball.id)?' selected':''}`;button.style.setProperty('--ball',ball.color);button.disabled=running;button.setAttribute('aria-pressed',String(selected.has(ball.id)));button.innerHTML=`<i></i><span>${ball.name}</span>`;button.addEventListener('click',()=>{selected.has(ball.id)?selected.delete(ball.id):selected.add(ball.id);renderPicker();drawIdle()});picker.append(button)});const chosenNames=palette.filter(ball=>selected.has(ball.id)).map(ball=>ball.name);selectedCount.textContent=`${selected.size}개`;selectedNames.textContent=chosenNames.length?chosenNames.join(' · '):'선택한 공이 없습니다.';if(!running&&!results.length)finishTotal.textContent=` / ${selected.size} 도착`;startButton.disabled=selected.size<2||running}
function drawBoard(){const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,'#173b59');bg.addColorStop(1,'#081523');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(143,190,218,.55)';ctx.lineWidth=4;[leftWall,rightWall].forEach(wall=>{ctx.beginPath();wall.forEach((point,index)=>index?ctx.lineTo(point.x,point.y):ctx.moveTo(point.x,point.y));ctx.stroke()});ctx.strokeStyle='rgba(73,227,223,.55)';ctx.lineWidth=2;ctx.strokeRect(3,3,W-6,H-6);ctx.fillStyle='#b9d6e6';ctx.font='900 12px sans-serif';ctx.textAlign='center';ctx.fillText('START',W/2,35);ctx.fillStyle='rgba(73,227,223,.17)';ctx.fillRect(82,finishY,56,34);for(let x=82;x<138;x+=14){ctx.fillStyle=((x/14)%2)?'#ffe43e':'#1b6871';ctx.fillRect(x,finishY,14,7)}ctx.fillStyle='#dffcff';ctx.fillText('FINISH',W/2,1188);
pins.forEach(pin=>{ctx.beginPath();ctx.arc(pin.x,pin.y,pin.r,0,Math.PI*2);ctx.fillStyle='#e7d5b4';ctx.fill();ctx.strokeStyle='#715f48';ctx.lineWidth=2;ctx.stroke()});bumpers.forEach((b,i)=>{ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle=i%2?'#f3c946':'#e94c3b';ctx.fill();ctx.strokeStyle='#fff4d8';ctx.lineWidth=6;ctx.stroke();ctx.beginPath();ctx.arc(b.x,b.y,b.r-11,0,Math.PI*2);ctx.strokeStyle='rgba(39,33,26,.5)';ctx.lineWidth=3;ctx.stroke()});rotors.forEach(rotor=>{const rail=rotorSegment(rotor);ctx.beginPath();ctx.moveTo(rail.x1,rail.y1);ctx.lineTo(rail.x2,rail.y2);ctx.strokeStyle='#57c7d5';ctx.lineWidth=12;ctx.lineCap='round';ctx.stroke();ctx.strokeStyle='#d8ffff';ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.arc(rotor.cx,rotor.cy,9,0,Math.PI*2);ctx.fillStyle='#fff6dc';ctx.fill();ctx.strokeStyle='#25848f';ctx.lineWidth=3;ctx.stroke()})}
function drawBall(ball){ctx.save();ctx.shadowColor=ball.color;ctx.shadowBlur=8;ctx.shadowOffsetY=2;ctx.beginPath();ctx.arc(ball.x,ball.y,R,0,Math.PI*2);const g=ctx.createRadialGradient(ball.x-3,ball.y-4,1,ball.x,ball.y,R);g.addColorStop(0,'#fff');g.addColorStop(.28,ball.color);g.addColorStop(1,ball.color);ctx.fillStyle=g;ctx.fill();ctx.shadowColor='transparent';ctx.strokeStyle='rgba(255,255,255,.9)';ctx.lineWidth=1.5;ctx.stroke();ctx.restore()}
function drawIdle(){drawBoard();const chosen=palette.filter(ball=>selected.has(ball.id));const gap=Math.min(28,(W-52)/Math.max(1,chosen.length-1));const start=W/2-gap*(chosen.length-1)/2;chosen.forEach((ball,index)=>drawBall({x:start+index*gap,y:74,color:ball.color}));if(!chosen.length){ctx.fillStyle='rgba(255,255,255,.55)';ctx.font='700 11px sans-serif';ctx.fillText('공을 선택하세요',W/2,75)}}
function collideCircle(ball,target,bounce=1.04){const dx=ball.x-target.x,dy=ball.y-target.y,min=R+target.r,dist=Math.hypot(dx,dy);if(!dist||dist>=min)return;const nx=dx/dist,ny=dy/dist,overlap=min-dist;ball.x+=nx*overlap;ball.y+=ny*overlap;const speed=ball.vx*nx+ball.vy*ny;if(speed<0){ball.vx-=(1+bounce)*speed*nx;ball.vy-=(1+bounce)*speed*ny}ball.vx+=(Math.random()-.5)*22}
function collideRail(ball,rail){const ax=rail.x1,ay=rail.y1,bx=rail.x2,by=rail.y2,abx=bx-ax,aby=by-ay,t=Math.max(0,Math.min(1,((ball.x-ax)*abx+(ball.y-ay)*aby)/(abx*abx+aby*aby))),target={x:ax+abx*t,y:ay+aby*t,r:6};collideCircle(ball,target,.92)}
function rotorSegment(rotor){const dx=Math.cos(rotor.angle)*rotor.length/2,dy=Math.sin(rotor.angle)*rotor.length/2;return{x1:rotor.cx-dx,y1:rotor.cy-dy,x2:rotor.cx+dx,y2:rotor.cy+dy}}
function collideRotor(ball,rotor){const rail=rotorSegment(rotor),ax=rail.x1,ay=rail.y1,abx=rail.x2-ax,aby=rail.y2-ay,t=Math.max(0,Math.min(1,((ball.x-ax)*abx+(ball.y-ay)*aby)/(abx*abx+aby*aby))),px=ax+abx*t,py=ay+aby*t,before=Math.hypot(ball.x-px,ball.y-py);collideRail(ball,rail);if(before<R+7){const rx=px-rotor.cx,ry=py-rotor.cy;ball.vx+=-rotor.speed*ry*.7;ball.vy+=rotor.speed*rx*.7}}
function collideBalls(){for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){const a=balls[i],b=balls[j];if(a.finished||b.finished)continue;const dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy),min=R*2;if(!dist||dist>=min)continue;const nx=dx/dist,ny=dy/dist,overlap=(min-dist)/2;a.x-=nx*overlap;a.y-=ny*overlap;b.x+=nx*overlap;b.y+=ny*overlap;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){const impulse=-rel*.88;a.vx-=impulse*nx;a.vy-=impulse*ny;b.vx+=impulse*nx;b.vy+=impulse*ny}}}
function update(dt,now){const elapsed=(now-startAt)/1000,gravity=500+Math.max(0,elapsed-12)*28,rescue=elapsed>20;rotors.forEach(rotor=>rotor.angle+=rotor.speed*dt);balls.forEach(ball=>{if(ball.finished||now<ball.releaseAt)return;ball.vy+=gravity*dt;ball.vx*=.998;ball.vy*=.999;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;const left=boundaryX(leftWall,ball.y)+R,right=boundaryX(rightWall,ball.y)-R;if(ball.x<left){ball.x=left;ball.vx=Math.abs(ball.vx)*.78+6}if(ball.x>right){ball.x=right;ball.vx=-Math.abs(ball.vx)*.78-6}if(rescue){ball.vy=Math.max(ball.vy,380)}else{pins.forEach(pin=>collideCircle(ball,pin,.84));bumpers.forEach(b=>collideCircle(ball,b,1.17));rotors.forEach(rotor=>collideRotor(ball,rotor))}if(elapsed>16&&ball.vy<105)ball.vy+=90;if(ball.y>finishY+R){ball.finished=true;ball.finishTime=elapsed;results.push(ball);renderRanking();if(results.length===balls.length)finishRace()}});collideBalls()}
function renderRanking(){ranking.textContent='';finishCount.textContent=String(results.length);finishTotal.textContent=` / ${balls.length||selected.size} 도착`;if(!results.length){const item=document.createElement('li');item.className='empty';item.textContent='순위 대기 중';ranking.append(item);return}results.forEach((ball,index)=>{const item=document.createElement('li');item.style.setProperty('--ball',ball.color);item.innerHTML=`<span class="place">${index+1}위</span><i class="dot"></i><strong></strong><time>${ball.finishTime.toFixed(2)}초</time>`;item.querySelector('strong').textContent=ball.name;ranking.append(item)})}
function frame(now){if(!running)return;const dt=Math.min(.022,(now-lastTime)/1000||.016);lastTime=now;update(dt,now);drawBoard();balls.forEach(drawBall);raf=requestAnimationFrame(frame)}
function prepareBalls(){const chosen=palette.filter(ball=>selected.has(ball.id));const gap=Math.min(28,(W-52)/Math.max(1,chosen.length-1));const left=W/2-gap*(chosen.length-1)/2;balls=chosen.map((ball,index)=>({ ...ball,x:left+index*gap,y:74-R,vx:(Math.random()-.5)*18,vy:0,releaseAt:performance.now()+index*130,finished:false,finishTime:0}))}
function beginRace(){if(selected.size<2){errorBox.textContent='공을 2개 이상 선택해 주세요.';return}cancelAnimationFrame(raf);errorBox.textContent='';results=[];renderRanking();running=true;renderPicker();resetButton.disabled=true;prepareBalls();let count=3;countdown.hidden=false;countdown.textContent=count;raceState.textContent='출발 준비';const timer=setInterval(()=>{count-=1;if(count>0){countdown.textContent=count;return}clearInterval(timer);countdown.textContent='GO!';raceState.textContent='경기 진행 중';setTimeout(()=>countdown.hidden=true,450);startAt=performance.now()+300;balls.forEach((ball,index)=>ball.releaseAt=startAt+index*150);lastTime=performance.now();raf=requestAnimationFrame(frame)},650)}
function finishRace(){running=false;cancelAnimationFrame(raf);raceState.textContent=`${results[0].name} 우승`;startButton.querySelector('span').textContent='다시 시작';startButton.disabled=false;resetButton.disabled=false;renderPicker()}
function resetSelection(){if(running)return;selected=new Set();balls=[];results=[];rotors.forEach(rotor=>rotor.angle=rotor.startAngle);ranking.innerHTML='<li class="empty">순위 대기 중</li>';finishCount.textContent='0';finishTotal.textContent=' / 0 도착';raceState.textContent='출전할 공을 선택하세요';startButton.querySelector('span').textContent='시작';errorBox.textContent='';renderPicker();drawIdle()}
startButton.addEventListener('click',beginRace);resetButton.addEventListener('click',resetSelection);renderPicker();drawIdle();
})();
