const canvas=document.querySelector('#wheel'),ctx=canvas.getContext('2d'),spinBtn=document.querySelector('#spin'),pointerLabel=document.querySelector('#pointerLabel'),itemsEl=document.querySelector('#items'),presetsEl=document.querySelector('#presets');
const newItem=document.querySelector('#newItem'),newWeight=document.querySelector('#newWeight'),addBtn=document.querySelector('#add'),saveName=document.querySelector('#saveName'),saveBtn=document.querySelector('#save');
const CURRENT='sgra88-wheel-current-v2',OLD_CURRENT='sgra88-wheel-current-v1',PRESETS='sgra88-wheel-presets-v2',OLD_PRESETS='sgra88-wheel-presets-v1',palette=['#ef1760','#2598df','#ffc928','#29bd91','#8d6de8','#ff714b','#3fcbd1','#f05cac','#6fb640','#ea9b26'];
let items=loadCurrent(),rotation=0,mode='idle',speed=.012,speedScale=1,last=performance.now(),stopStart=0,stopFrom=0,stopDistance=0,stopDuration=4500;
let pointerText='';
function cleanWeight(v){return Math.min(999,Math.max(1,Math.round(Number(v)||1)))}
function consolidate(list){const grouped=[];for(const raw of list){const text=String(raw.text||'항목').trim()||'항목',key=text.toLocaleLowerCase('ko-KR'),found=grouped.find(x=>x.key===key),weight=cleanWeight(raw.weight);if(found)found.weight+=weight;else grouped.push({text,color:raw.color||palette[grouped.length%palette.length],weight,key})}return grouped.map(({key,...x})=>x)}
function loadCurrent(){let value=null;try{value=JSON.parse(localStorage.getItem(CURRENT)||localStorage.getItem(OLD_CURRENT))}catch{}if(Array.isArray(value)&&value.length>1)return consolidate(value);return[{text:'당첨',color:palette[0],weight:1},{text:'한번 더',color:palette[1],weight:1},{text:'꽝',color:palette[2],weight:3}]}
function persist(){localStorage.setItem(CURRENT,JSON.stringify(items))}
function presets(){try{return JSON.parse(localStorage.getItem(PRESETS)||localStorage.getItem(OLD_PRESETS))||{}}catch{return {}}}
function savePresets(v){localStorage.setItem(PRESETS,JSON.stringify(v))}
function totalWeight(){return items.reduce((sum,x)=>sum+cleanWeight(x.weight),0)}
function fitText(text,max,slice){let size=Math.min(30,Math.max(12,14+slice*9));ctx.font=`900 ${size}px 'Noto Sans KR',sans-serif`;while(ctx.measureText(text).width>max&&size>10){size--;ctx.font=`900 ${size}px 'Noto Sans KR',sans-serif`}return size}
function draw(){const w=canvas.width,c=w/2,r=w*.46,tau=Math.PI*2,total=totalWeight();ctx.clearRect(0,0,w,w);ctx.save();ctx.translate(c,c);ctx.rotate(rotation);let angle=0;items.forEach(item=>{const slice=tau*item.weight/total,a=angle,b=a+slice;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a,b);ctx.closePath();ctx.fillStyle=item.color;ctx.fill();ctx.strokeStyle='#ffffff99';ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.rotate(a+slice/2);ctx.translate(r*.62,0);ctx.rotate(Math.PI/2);const size=fitText(item.text,r*.56,slice);ctx.font=`900 ${size}px 'Noto Sans KR',sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=Math.max(3,size*.16);ctx.strokeStyle='#203340';ctx.strokeText(item.text,0,0);ctx.fillStyle='#fff';ctx.fillText(item.text,0,0);ctx.restore();angle=b});ctx.beginPath();ctx.arc(0,0,r,0,tau);ctx.lineWidth=9;ctx.strokeStyle='#294550';ctx.stroke();ctx.beginPath();ctx.arc(0,0,24,0,tau);ctx.fillStyle='#fff';ctx.fill();ctx.lineWidth=8;ctx.strokeStyle='#294550';ctx.stroke();ctx.restore()}
function winningIndex(){const tau=Math.PI*2,total=totalWeight(),local=(((-Math.PI/2-rotation)%tau)+tau)%tau;let angle=0;for(let i=0;i<items.length;i++){angle+=tau*items[i].weight/total;if(local<angle)return i}return items.length-1}
function updatePointerLabel(){const item=items[winningIndex()];if(!item||item.text===pointerText)return;pointerText=item.text;pointerLabel.textContent=item.text;pointerLabel.style.borderColor=item.color;pointerLabel.style.textShadow=`0 0 18px ${item.color}`}
function loop(now){const dt=Math.min(40,now-last);last=now;if(mode==='spinning')rotation+=speed*speedScale*dt;else if(mode==='stopping'){const t=Math.min(1,(now-stopStart)/stopDuration),m=speed*speedScale*stopDuration/stopDistance,p=(-2*t*t*t+3*t*t)+m*(t*t*t-2*t*t+t);rotation=stopFrom+stopDistance*p;if(t>=1)finish()}rotation%=Math.PI*2;draw();updatePointerLabel();requestAnimationFrame(loop)}
function start(){if(items.length<2)return;mode='spinning';spinBtn.textContent='멈춤';spinBtn.classList.add('stop');setEditing(false)}
function stop(){if(mode!=='spinning')return;mode='stopping';spinBtn.textContent='감속 중…';spinBtn.disabled=true;stopStart=performance.now();stopFrom=rotation;stopDistance=Math.max(Math.PI*5,speed*speedScale*stopDuration/2+(Math.random()-.5)*Math.PI*.8)}
function finish(){mode='idle';spinBtn.textContent='시작';spinBtn.classList.remove('stop');spinBtn.disabled=false;setEditing(true)}
function setEditing(enabled){document.querySelectorAll('aside input,aside button,.speed button').forEach(el=>el.disabled=!enabled)}
function renderItems(){items=consolidate(items);itemsEl.innerHTML='';const total=totalWeight();items.forEach((item,i)=>{const row=document.createElement('div');row.className='item';const color=document.createElement('input');color.type='color';color.value=item.color;color.title='색상';const text=document.createElement('input');text.type='text';text.maxLength=24;text.value=item.text;const weight=document.createElement('input');weight.type='number';weight.className='weight';weight.min='1';weight.max='999';weight.value=item.weight;weight.setAttribute('aria-label',`${item.text} 가중치`);const probability=document.createElement('span');probability.className='probability';probability.textContent=`${(item.weight/total*100).toFixed(1)}%`;const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.title='삭제';color.oninput=()=>{item.color=color.value;persist();draw()};text.oninput=()=>{item.text=text.value||`항목 ${i+1}`;persist();draw()};text.onchange=()=>{items=consolidate(items);renderItems();draw()};weight.onchange=()=>{item.weight=cleanWeight(weight.value);renderItems();draw()};remove.onclick=()=>{if(items.length<=2)return alert('항목은 최소 2개가 필요합니다.');items.splice(i,1);persist();renderItems();draw()};row.append(color,text,weight,probability,remove);itemsEl.append(row)});persist()}
function addItem(){const text=newItem.value.trim(),weight=cleanWeight(newWeight.value);if(!text||items.length>=20)return;const found=items.find(x=>x.text.trim().toLocaleLowerCase('ko-KR')===text.toLocaleLowerCase('ko-KR'));if(found)found.weight+=weight;else items.push({text,color:palette[items.length%palette.length],weight});newItem.value='';newWeight.value='1';renderItems();draw();newItem.focus()}
function renderPresets(){const saved=presets();presetsEl.innerHTML='';Object.keys(saved).forEach(name=>{const data=consolidate(saved[name]),row=document.createElement('div');row.className='preset';const load=document.createElement('button');load.className='load';load.textContent=name;const count=document.createElement('button');count.textContent=`${data.length}항목`;const remove=document.createElement('button');remove.className='remove';remove.textContent='삭제';load.onclick=count.onclick=()=>{items=data.map(x=>({...x}));persist();renderItems();draw()};remove.onclick=()=>{delete saved[name];savePresets(saved);renderPresets()};row.append(load,count,remove);presetsEl.append(row)});if(!Object.keys(saved).length)presetsEl.innerHTML='<small>저장된 돌림판이 없습니다.</small>'}
spinBtn.onclick=()=>mode==='idle'?start():mode==='spinning'&&stop();addBtn.onclick=addItem;newItem.onkeydown=e=>{if(e.key==='Enter')addItem()};newWeight.onkeydown=e=>{if(e.key==='Enter')addItem()};saveBtn.onclick=()=>{const name=saveName.value.trim();if(!name)return saveName.focus();const saved=presets();saved[name]=items.map(x=>({...x}));savePresets(saved);saveName.value='';renderPresets()};document.querySelectorAll('.speed button').forEach(b=>b.onclick=()=>{speedScale=Number(b.dataset.speed);document.querySelectorAll('.speed button').forEach(x=>x.classList.toggle('selected',x===b))});
renderItems();renderPresets();draw();requestAnimationFrame(loop);
