const canvas=document.querySelector('#wheel'),ctx=canvas.getContext('2d'),spinBtn=document.querySelector('#spin'),winnerBox=document.querySelector('#winner'),winnerText=winnerBox.querySelector('strong'),itemsEl=document.querySelector('#items'),presetsEl=document.querySelector('#presets');
const newItem=document.querySelector('#newItem'),addBtn=document.querySelector('#add'),saveName=document.querySelector('#saveName'),saveBtn=document.querySelector('#save'),againBtn=document.querySelector('#again');
const CURRENT='sgra88-wheel-current-v1',PRESETS='sgra88-wheel-presets-v1',palette=['#ef1760','#2598df','#ffc928','#29bd91','#8d6de8','#ff714b','#3fcbd1','#f05cac','#6fb640','#ea9b26'];
let items=loadCurrent(),rotation=0,mode='idle',speed=.007,speedScale=1,last=performance.now(),stopStart=0,stopFrom=0,stopDistance=0,stopDuration=4800;
function loadCurrent(){try{const v=JSON.parse(localStorage.getItem(CURRENT));if(Array.isArray(v)&&v.length>1)return v}catch{}return[{text:'꽝',color:palette[0]},{text:'당첨',color:palette[1]},{text:'한번 더',color:palette[2]},{text:'아쉽다',color:palette[3]}]}
function persist(){localStorage.setItem(CURRENT,JSON.stringify(items))}
function presets(){try{return JSON.parse(localStorage.getItem(PRESETS))||{}}catch{return {}}}
function savePresets(v){localStorage.setItem(PRESETS,JSON.stringify(v))}
function fitText(text,max){let size=Math.min(30,210/items.length);ctx.font=`900 ${size}px 'Noto Sans KR',sans-serif`;while(ctx.measureText(text).width>max&&size>10){size--;ctx.font=`900 ${size}px 'Noto Sans KR',sans-serif`}return size}
function draw(){const w=canvas.width,h=canvas.height,cx=w/2,cy=h/2,r=w*.46,slice=Math.PI*2/items.length;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(cx,cy);ctx.rotate(rotation);items.forEach((item,i)=>{const a=i*slice,b=a+slice;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a,b);ctx.closePath();ctx.fillStyle=item.color;ctx.fill();ctx.strokeStyle='#ffffff88';ctx.lineWidth=3;ctx.stroke();ctx.save();ctx.rotate(a+slice/2);ctx.translate(r*.62,0);ctx.rotate(Math.PI/2);const size=fitText(item.text,r*.58);ctx.font=`900 ${size}px 'Noto Sans KR',sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=Math.max(3,size*.16);ctx.strokeStyle='#203340';ctx.strokeText(item.text,0,0);ctx.fillStyle='#fff';ctx.fillText(item.text,0,0);ctx.restore()});ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.lineWidth=9;ctx.strokeStyle='#294550';ctx.stroke();ctx.beginPath();ctx.arc(0,0,24,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.lineWidth=8;ctx.strokeStyle='#294550';ctx.stroke();ctx.restore()}
function winningIndex(){const tau=Math.PI*2,local=(((-Math.PI/2-rotation)%tau)+tau)%tau;return Math.floor(local/(tau/items.length))%items.length}
function loop(now){const dt=Math.min(40,now-last);last=now;if(mode==='spinning')rotation+=speed*speedScale*dt;else if(mode==='stopping'){const t=Math.min(1,(now-stopStart)/stopDuration),m=speed*speedScale*stopDuration/stopDistance;const p=(-2*t*t*t+3*t*t)+m*(t*t*t-2*t*t+t);rotation=stopFrom+stopDistance*p;if(t>=1)finish()}rotation%=Math.PI*2;draw();requestAnimationFrame(loop)}
function start(){if(items.length<2)return;winnerBox.hidden=true;mode='spinning';spinBtn.textContent='멈춤';spinBtn.classList.add('stop');spinBtn.disabled=false;setEditing(false)}
function stop(){if(mode!=='spinning')return;mode='stopping';spinBtn.textContent='감속 중…';spinBtn.disabled=true;stopStart=performance.now();stopFrom=rotation;stopDuration=4500;stopDistance=speed*speedScale*stopDuration/2+(Math.random()-.5)*Math.PI*.8;stopDistance=Math.max(Math.PI*5,stopDistance)}
function finish(){mode='idle';spinBtn.textContent='시작';spinBtn.classList.remove('stop');spinBtn.disabled=false;const winner=items[winningIndex()];winnerText.textContent=winner.text;winnerText.style.color=winner.color;winnerBox.hidden=false;setEditing(true)}
function setEditing(enabled){document.querySelectorAll('aside input,aside button,.speed button').forEach(el=>el.disabled=!enabled)}
function renderItems(){itemsEl.innerHTML='';items.forEach((item,i)=>{const row=document.createElement('div');row.className='item';const color=document.createElement('input');color.type='color';color.value=item.color;color.title='색상';const text=document.createElement('input');text.type='text';text.maxLength=24;text.value=item.text;const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.title='삭제';color.oninput=()=>{item.color=color.value;persist();draw()};text.oninput=()=>{item.text=text.value||`항목 ${i+1}`;persist();draw()};remove.onclick=()=>{if(items.length<=2)return alert('항목은 최소 2개가 필요합니다.');items.splice(i,1);persist();renderItems();draw()};row.append(color,text,remove);itemsEl.append(row)});persist()}
function addItem(){const text=newItem.value.trim();if(!text||items.length>=20)return;items.push({text,color:palette[items.length%palette.length]});newItem.value='';renderItems();draw();newItem.focus()}
function renderPresets(){const saved=presets();presetsEl.innerHTML='';Object.keys(saved).forEach(name=>{const row=document.createElement('div');row.className='preset';const load=document.createElement('button');load.className='load';load.textContent=name;const count=document.createElement('button');count.textContent=`${saved[name].length}칸`;const remove=document.createElement('button');remove.className='remove';remove.textContent='삭제';load.onclick=count.onclick=()=>{items=saved[name].map(x=>({...x}));persist();renderItems();draw()};remove.onclick=()=>{delete saved[name];savePresets(saved);renderPresets()};row.append(load,count,remove);presetsEl.append(row)});if(!Object.keys(saved).length)presetsEl.innerHTML='<small>저장된 돌림판이 없습니다.</small>'}
spinBtn.onclick=()=>mode==='idle'?start():mode==='spinning'&&stop();againBtn.onclick=()=>{winnerBox.hidden=true;start()};addBtn.onclick=addItem;newItem.onkeydown=e=>{if(e.key==='Enter')addItem()};saveBtn.onclick=()=>{const name=saveName.value.trim();if(!name)return saveName.focus();const saved=presets();saved[name]=items.map(x=>({...x}));savePresets(saved);saveName.value='';renderPresets()};document.querySelectorAll('.speed button').forEach(b=>b.onclick=()=>{speedScale=Number(b.dataset.speed);document.querySelectorAll('.speed button').forEach(x=>x.classList.toggle('selected',x===b))});
renderItems();renderPresets();draw();requestAnimationFrame(loop);
